### ISSUE TITLE
David Wolf: Secret Agent no MIDI music

### ISSUE THREAD

**Issue by jharrison03** [dosemu2/dosemu2#2026] opened 2023-06-23 01:49 UTC
**Describe the bug**
The game David Wolf: Secret Agent runs but doesn't present any MIDI music.

**To Reproduce**
Run "AGENT.EXE" with DOSemu configured for MUNT with MPU IRQ set on 2 (IRQ 2 is a hard requirement based on the table found here -- https://github.com/bjt42/softmpu/wiki/Compatible-Intelligent-Mode-Games)

**Attach program/game binaries or provide an URL**
[wolf.zip](https://github.com/dosemu2/dosemu2/files/11842976/wolf.zip)

**Attach the log**
[boot_log.zip](https://github.com/dosemu2/dosemu2/files/11843017/boot_log.zip)
[dosemurc.zip](https://github.com/dosemu2/dosemu2/files/11843023/dosemurc.zip)

**A regression?**
No, AFAIK, it has never worked.

**Additional info**
See here -- https://github.com/bjt42/softmpu/issues/27

This game seems problematic in general with MIDI.  It does run correctly under DOSbox and DOSbox-X and on PC hardware with very compatible Roland interfaces (LAPCI-I and MusicQuest cards based on Z8 controller but not the later variants based on the Intel 8051 even with SoftMPU).  The Intel-based cards are the MusicQuest PC MIDI Card II and are 'non-intelligent' so this is expected behavior, but should work with SoftMPU.

This isn't the SoftMPU project, but I mention this because the failure modes here might share some commonality.

**Comment by stsp** [comment] 2023-06-23 06:42
> MUNT with MPU IRQ set on 2 (IRQ 2 is a hard requirement based on the table found here

No, its a misunderstanding.
The hard requirement is to set it to 2
in the game's setup (if there is such,
or maybe it hard-codes it to 2 w/o any
setup).
But in dosemu2 config you need to
set it to 9.
I added the patch now that fixes up
2 and changes it to 9.

**Comment by jharrison03** [comment] 2023-06-23 06:52
The game has no setup and the program itself expects the interface to be on IRQ 2.

Setting $_mpu_irq_mt32 = (9) in dosemurc doesn't produce any sound.

**Comment by stsp** [comment] 2023-06-23 07:01
> Setting $_mpu_irq_mt32 = (9) in dosemurc doesn't produce any sound.

That's because we do not implement
the intelligent mode properly, but one
step at a time. You need to set it to 9
and I need to look into dosbox sources
to see how difficult is it to implement
the intelligent mode.

**Comment by stsp** [comment] 2023-06-23 08:23
What midi port number do those setup-less
games expect?

**Comment by runderwo** [comment] 2023-06-23 15:04
> > Setting $_mpu_irq_mt32 = (9) in dosemurc doesn't produce any sound.
> 
> That's because we do not implement the intelligent mode properly, but one step at a time. You need to set it to 9 and I need to look into dosbox sources to see how difficult is it to implement the intelligent mode.

It's already done on an older branch - https://github.com/runderwo/dosemu2/tree/mpu401
It works but the music slows down in Gateway if a key is not pressed.  I think it needs to bypass idle/hogthreshold but I didn't have time to figure it out.  At the time your opinion was "this is unnecessary, just use softmpu".

I think it should be easy to rebase this.  The programs I tested at the time work fine (Cakewalk, Sierra games, etc).

**Comment by jharrison03** [comment] 2023-06-23 15:12
_I think it needs to bypass idle/hogthreshold but I didn't have time to figure it out. At the time your opinion was "this is unnecessary, just use softmpu"._

Unless something has changed, SoftMPU doesn't work with DOSemu because it doesn't support either the EMM386 or QEMM style port trapping APIs.

**Comment by runderwo** [comment] 2023-06-23 15:20
> Unless something has changed, SoftMPU doesn't work with DOSemu because it doesn't support either the EMM386 or QEMM style port trapping APIs.

That's right, the idea was to implement those APIs and use softmpu instead of porting dosbox code.  I think it's a matter of taste and it wouldn't be a bad thing to have the port trapping APIs.  On the other hand users are still missing an important hardware emulation feature.

**Comment by jharrison03** [comment] 2023-06-23 17:09
> What midi port number do those setup-less games expect?

330h.  This was probably because the 'original' MPU-401 8-bit ISA card was fixed at this address and IRQ 2 (as well as the MCA version).  You could change the IRQ to 3, 4, 5 or 7 if you were willing to modify the card.  This would break some game compatibility though for the titles that expected these particular resources (like the game in question here).

It's only a handful of games that this affects though.

**Comment by stsp** [comment] 2023-06-23 17:21
> At the time your opinion was "this is unnecessary, just use softmpu".

No, please, don't blackmail me. :)
The opinion was that it is unnecessary
*as part of an sb16*. It would be good
as a separate board, *or*  softmpu.
Considering separate board, I think
they need to have different IO ports
with mpu401 of sb16.

**Comment by stsp** [comment] 2023-06-23 17:26
> It's already done on an older branch

Thanks, that probably should be used as a
base, but it should be done as a separate
board (the same opinion was expressed
back then).

**Comment by stsp** [comment] 2023-06-23 17:28
Also if you want to work on that, I encourage
you to add yourself to FUNDING.yml in a hope
@jharrison03 (or anyone else) can donate to
you on a patreon. I think the more people in
FUNDING.yml we have, the better, but so far
I am alone there.

**Comment by stsp** [comment] 2023-06-23 17:34
> 330h. This was probably because the 'original' MPU-401 8-bit ISA card was fixed at this address

OK so I have a sneaky plan to alter
the IO port for sb16's MPU then...
Although this will add a headache
to the users, so not sure what is the
best way of having 2 MPUs concurrently.

**Comment by jharrison03** [comment] 2023-06-23 17:34
> Also if you want to work on that, I encourage you to add yourself to FUNDING.yml in a hope @jharrison03 (or anyone else) can donate to you on a patreon. I think the more people in FUNDING.yml we have, the better, but so far I am alone there.

Ask and ye shall receive.

**Comment by stsp** [comment] 2023-06-23 17:36
> Ask and ye shall receive.

Thanks for confirming!
Hope @runderwo will create a PR to
update FUNDING.yml. :)

**Comment by runderwo** [comment] 2023-06-23 17:38
> > At the time your opinion was "this is unnecessary, just use softmpu".
> 
> No, please, don't blackmail me. :) The opinion was that it is unnecessary _as part of an sb16_. It would be good as a separate board, _or_ softmpu. Considering separate board, I think they need to have different IO ports with mpu401 of sb16.

I'm not sure that will really work -- both MPU401 and SB16 UART are almost always configured at port 330.  I think it makes more sense to be a configuration option, perhaps best switching the behavior at runtime through blaster.com (or whatever it's called now).  Although I really don't see the drawback of a "mutant" SB16 that happens to have an intelligent mode MPU401, runtime switching would cover any corner case that arises.

**Comment by jharrison03** [comment] 2023-06-23 17:41
I don't see any disadvantage with a 'real MPU-401', and a SB with its MIDI port disabled.  That's how it's probably most commonly configured in the case of real hardware.

**Comment by stsp** [comment] 2023-06-23 17:44
OK 1 thing to note is that @jharrison03 already
became _my_ patron on patreon... We can still
amend that if Ryan adds himself to FUNDING.yml. :)

> Although I really don't see the drawback of a "mutant" SB16 that happens to have
> an intelligent mode MPU401

The problem is not in having the mutant.
The problem is that sb's MPU has a properly
defined use-case: uart to the GM-compatible
device. While another mpu can be permanently
connected to munt or alike.

**Comment by jharrison03** [comment] 2023-06-23 17:46
_OK 1 thing to note is that @jharrison03 already
became my patron on patreon... We can still
amend that if Ryan adds himself to FUNDING.yml. :)_

Absolutely.

**Comment by stsp** [comment] 2023-06-23 17:51
> I don't see any disadvantage with a 'real MPU-401', and a SB with its MIDI port disabled.
> That's how it's probably most commonly configured in the case of real hardware.

How do you configure it this way?
I don't remember any jumper on SB16
board to disable MPU. I think you had
to configure it for a non-330 port to not
conflict with the mt32 MPU?

**Comment by jharrison03** [comment] 2023-06-23 17:54
What I do, in the case of my 'real' HW, is the MPU-401 is sitting at 330 IO and IRQ 2.  I have a PAS16 though and not an SB, so I can actually disable the MPU-401 portion.

I would imagine in the case of an actual SB, I would move the IO port to 300 (I think that's the only other option).  But that's just a guess.

**Comment by stsp** [comment] 2023-06-23 18:07
https://www.os2museum.com/wp/sound-blaster-diagnose-and-disabled-mpu-401/
It appears there is a mpu-disable jumper,
but then diagnose.exe doesn't work.
Still I think the better solution is to move
to 0x300. But I don't know how painful
that's going to be: the progs that take
the settings from `BLASTER` var are
going to be fine, but I suppose not all
progs are that polite.

**Comment by jharrison03** [comment] 2023-06-23 18:47
_the progs that take
the settings from BLASTER var are
going to be fine, but I suppose not all
progs are that polite._

Games probably don't look at the environment for MIDI configuration, and that's probably what most people would be interested in.  Sequencer software will almost definitely allow configuration through its settings.

The only SW, AFAIK, that honors the MIDI= variable is Creative's shovelware.  The MPU-401 is not a Creative or SB thing, but a Roland thing.

The MPU really needs be at IO 330 and IRQ 2 because that's where much software expects it to be.  Anything other than this and it's going to cause compatibility issues.

**Comment by stsp** [comment] 2023-06-23 18:56
> The MPU really needs be at IO 330 and IRQ 2

SB's MPU was never at irq2, and we
are talking about it. But unfortunately
it uses port 330.

**Comment by jharrison03** [comment] 2023-06-23 18:59
That's the whole thing.

Ideally we (or I) want to emulate a Roland MPU-401, not whatever Creative Labs is doing on the SB.  And Roland's cards were hard coded for these resources - ie. you couldn't change them without a soldering iron.

The way DOSbox is handling the MPU-401 is perfect.  That's how I think DOSEmu should also handle it.

**Comment by stsp** [comment] 2023-06-23 19:17
I am not going to move mt32 mpu, I
am going to move sb mpu, which is
connected to a gm device.

**Comment by jharrison03** [comment] 2023-06-23 19:27
The GM device can be anywhere, but the 'MT-32 style' device (MUNT) should appear to be on an interface that is MPU-401 compatible (this means a co-processed, add-in MIDI card that is compatible with Roland's implementation - which a Sound Blaster is NOT).

This is not really hardware stuff, but how ancient software expects things to be and there's a lot of it out there, at least until GM took over.

But there's no logical reason why a GM and LA synth can't both be on the same MPU-401.  MIDI allows for this and that's a common thing to do (ie. a PC with an SC-55 chained to an MT-32 or CM-32L via. the MIDI THRU connector).

**Comment by stsp** [comment] 2023-06-23 19:27
Actually there is a backward-cpmpat
scheme. I can move sb mpu to 300, but
connect mt32 mpu to gm device as well,
unless the mt32-capable device (like
munt) is enabled.

**Comment by stsp** [comment] 2023-06-23 19:30
Not sure about the chaining, can you
provide documentation on that?

**Comment by jharrison03** [comment] 2023-06-23 19:32
I would imagine that would be in some type of MIDI spec, but that's what I do - MPU-401 interface OUT into SC-55 MIDI IN, then SC-55 MIDI THRU into CM-32L.

Both devices play at the same time, and you mute the one you don't want to hear.  That may not be optimal/convenient for an emulator, however.

**Comment by jharrison03** [comment] 2023-06-23 19:40
I wouldn't personally care if GM or MT-32 were mutually exclusive options in dosemurc.  I don't want to complicate this with MIDI device chaining.  It's not necessary.

**Comment by stsp** [comment] 2023-06-23 19:58
I dont remember the midi spec by heart,
but I think the only way to do such
multiplexing is to use sysexes to direct
the midi messages to your sc-55, and
bypass those w/o sysexes. That said,
your sc-55 is probably not gm-compatible,
so it can do this. I really don't think
gm-compatible devs have such a pass-through,
and I don't know if roland's ones have it,
but I would guess not?
I mean, can you re-connect the chain to
have your sc-55 at the end? Or can you
chain w/o sc-55? Or can you chain 3 devs?

**Comment by stsp** [comment] 2023-06-23 19:59
Yes, I also dont want chaining.
And I'd like to avoid a run-time or
config-time switch either.

**Comment by jharrison03** [comment] 2023-06-23 20:18
This particular SC-55 is not GM compatible in the strictest sense because it's an early GS device, but later SC-55's were GM compatible and retained the MIDI THRU port.  I don't know what happens with the GM-compatible units if used in this fashion.

Anyhow, not anything necessary for DOSemu I think.

**Comment by stsp** [comment] 2023-06-23 20:38
Yes, chaining is not necessary.
Since we already have quite a few mt32
games working in uart mode, I can
prototype this board split without
implementing anything new.

**Comment by stsp** [comment] 2023-06-26 18:53
I pushed the patch-set that adds
the initial mt32 impl. Without an
intelligent mode for now, so basically
its not any better than before. :)
But it is now a separate device on
port 0x330, whereas sb's moved
to 0x300.

This is the only thing I wanted from
@runderwo before reviewing his
intelli mode work. But it turned out
to be a quite complicated work, so
I had to do it myself.

Maybe Ryan can now continue his
intelli mode work? I'll be much more
positive about it now, since all the
needed infrastructure is in place.

Also I think some pause is needed to
see if any users are going to be hit
by this rather radical change. I really
tried to make it unobservable under
default configs, but who knows what
custom configs this will break...

Also I've noticed quite some bugs,
and hopefully fixed them, so
@jschwartzenberg could you please
re-test the games that had problems
with the sound playback?

**Comment by jharrison03** [comment] 2023-06-29 21:36
I really don't want to be a pain-in-the-ass with this.  I think I might not have the technical knowledge/vocabulary to articulate exactly what the issue is here, so let me try to explain what I see, from a user's POV --

Prior to these updates, there wasn't any general problems with intelligent mode games.  In fact, most all of them worked.  These patches regress other stuff - for example, if I put the MPU-401 "MT32" port back to 9 from 2, than DUMP.EXE freezes again (I reported this previously, and the advice at the time was to change the MPU-401 IRQ to 2)...

The intelligent mode games that didn't work, are the ones on the list from the SoftMPU Wiki that state they require an "MPU IRQ".  I assume what this means, is the program installs an interrupt handler to deal with timer functions (and whatever else a real MPU-401 does) generated by the HW. These are the programs that didn't work.  And it's a small list.

The way it is now is very confusing, and I don't think the problem is with SB/vs. MPU-401 port addresses or anything like that.

I think, there should just be one setting for MPU-401 IO port and IRQ, adhering to what Roland does, and forget anything about what a Sound Blaster does, or what hardware is 'virtually' connected to it - be it GM or LA module or whatever, because it shouldn't matter.  All of that will work on an interface that is actually MPU-401 compliant.

**Comment by stsp** [comment] 2023-06-30 02:07
I dont understand what you mean.
The only regression reported so far was
#2033 and its now fixed.
What is dump.exe?
If its regressed - attach it.
Also not sure what is "put
port back to 9 from 2".
Its not a port, its irq.
And you dont need to do anything
because in dosemu its set to 9 by
default, and in dos progs its set to
2 by default, none needing the change.
I suspect all the regressions are
because you do something when
nothing should be done.

**Comment by stsp** [comment] 2023-07-01 17:24
I pushed the `mt32` branch with
the softmpu rip-off. It seems (from
the log) that irqs are working, but
I don't hear any sound yet.
Is there some test for intelli mode?

**Comment by stsp** [comment] 2023-07-01 19:09
Seems to work, enjoy.

**Closed as completed** 2023-07-01 19:08 UTC

**Comment by stsp** [comment] 2023-07-02 06:58
Btw, this probably shows rather clearly
why I said 10 years ago that Ryan's code
is doomed. Hacking in dspio.c leads
nowhere, while with a small refactoring
you can just compile the softmpu sources
in a separate dir, and that took just half of
a day.

**Comment by jharrison03** [comment] 2023-07-06 11:35
> I pushed the `mt32` branch with the softmpu rip-off. It seems (from the log) that irqs are working, but I don't hear any sound yet. Is there some test for intelli mode?

The David Wolf game is a good litmus test for compatibility which is why I used this as an example (not because it's a good game).  I'll test this ASAP -- I had a PSU die on me during a holiday so I'll test this ASAP as soon as it arrives in the mail and thank you for looking into this.

**Comment by stsp** [comment] 2023-07-06 14:16
Test appears unneeded, I've found the
problem. Hope everything now works.

**Comment by jharrison03** [comment] 2023-07-06 16:40
You've nailed this and I can't thank you enough for this fix.   It's all working properly now.

**Comment by stsp** [comment] 2023-07-06 16:49
The fix doesn't matter.
What matters is that I added the
intelligent mode from softmpu.
Initially it didn't work right, but then
I've found the problem, so the "bug"
and "fix" part doesn't matter.

**Comment by stsp** [comment] 2023-07-06 16:53
But good to know that things work. :)

**Comment by jharrison03** [comment] 2023-07-06 16:55
You bet your ass it works :)
