### ISSUE TITLE
WPDOS 6.x won't start with $_cpu_emu = “vm86”

### ISSUE THREAD

**Issue by emendelson** [dosemu2/dosemu2#1147] opened 2020-05-11 12:39 UTC
**Describe the bug**
With default settings, WPDOS 6.x crashes dosemu2.

**To Reproduce**
Install WPDOS 6.x into drive_c, typically copying from an existing system the folders named WP62, WPC62DOS, BTFONTS, and PSFONTS (although the last three aren't essential)

**Attach program/game binaries or provide an URL**
To the devs: if you need the WP6.x files, please send a mail message to the address found on this page: http://wpdos.org/feedback.html

**Attach the log**

[boot.log](https://github.com/dosemu2/dosemu2/files/4609573/boot.log)

**Additional info**
No customizations done. But WPDOS 6.x starts if I edit dosemrc and use the line:

`$_cpu_emu = “vm86sim”`

**Comment by stsp** [comment] 2020-05-11 13:40
I tried wp5, but it seems to work.
So please mail me wp6.

**Comment by emendelson** [comment] 2020-05-11 15:39
WP5 works perfectly, but WP62 doesn’t. Here’s a self-contained folder:

http://www.columbia.edu/~em36/WPDOS62.7z <http://www.columbia.edu/~em36/WPDOS62.7z>

**Comment by stsp** [comment] 2020-05-11 23:29
It starts perfectly for me.
I only fixed the oddity on exit.
The problem is likely in a linux kernel,
yours is 4.15, which is quite old.
Recent ubuntu kernels prior
to 5.4.0-19 have KVM completely
broken, but that's probably not your
case. Anyway, try to upgrade your
kernel and we'll see.

**Comment by emendelson** [comment] 2020-05-11 23:39
I'm actually testing this in Ubuntu 20.04, running in VMware Workstation - I haven't used that ancient system for years and years. This is very strange.

I renamed my .dosemurc so that I would start with the default configuration, and these commands caused dosemu to freeze (not shut down):

`cd wp62`
`wp`

Here's the boot log:

[boot.log](https://github.com/dosemu2/dosemu2/files/4612621/boot.log)

Can't imagine why it works on your end...

**Comment by andrewbird** [comment] 2020-05-11 23:55
>KVM: error opening /dev/kvm: No such file or directory
KVM not available: No such file or directory
using CPU emulation for vm86()

On Ubuntu you need to install `qemu-kvm`,  add yourself into the kvm group, and logout / back in again before KVM will work for Doesemu.

**Comment by emendelson** [comment] 2020-05-12 00:01
I've now done exactly that, but WPDOS 6.2 still won't open and I have to force-close the emulator.

**Comment by stsp** [comment] 2020-05-12 00:07
No you didn't.
Good spot Andrew, I now can reproduce
with JIT.

**Comment by andrewbird** [comment] 2020-05-12 00:08
I can't say I've ever tried kvm inside a vmware guest though.

**Comment by emendelson** [comment] 2020-05-12 00:13
You're right - I didn't do all the steps listed here, only installed qemu-kvm itself:

https://help.ubuntu.com/community/KVM/Installation

I'll do it right when I'm back at my machine later on.

**Comment by stsp** [comment] 2020-05-12 01:10
Doesn't seem to be a regression.
Bart would you like to take a look?

**Comment by emendelson** [comment] 2020-05-12 01:44
This problem existed back in 2010 - I mention it on my old web page.

**Comment by emendelson** [comment] 2020-05-12 02:28
Of course you're right. I'm trying this out with Ubuntu 18.04 on a Mac running Parallels Desktop. I turned on nested virtualization in the Parallels setting, and, after installing kvm, WPDOS 6.2 ran as expected.

**Comment by stsp** [comment] 2020-06-01 09:47
This looks very similar to #86 .
If I remove the cached jit code nodes from
avl, then WP runs fine.
I was chasing it for 5 years.
I have a printed book about avl already,
so if this bug escapes from me again, then
I don't know what to do. :)
Off to reading the book.

**Comment by stsp** [comment] 2020-06-13 23:27
The bug stops happening if I disable
re-execution of CALLd opcode (via InterOps).

**Comment by bartoldeman** [comment] 2020-06-14 11:41
When trying to make `Tree_InvalidateNodePage` to not necessarily run on whole pages I ran into a tricky issue with BreakNode again that popped up years ago (commits 12cb5549 and 221914a). However just checking the addr here is not sufficient if the length is too long.
Right now with NOJUMPS eliminated we have a more simpler structure where `G->seqbase == G->key` at all times and that will allow to simplify BreakNode.

Perhaps that's not related to this bug directly but I'd let you know as a possible avenue -- I'll submit some PRs later, need to go now.

**Comment by stsp** [comment] 2020-06-14 12:01
Yes, I was always wondering why
do we need both key and seqbase
if they are always equal.
From your brief description here, I
can't see any obvious problem with
BreakNode, i.e. I thought knowing
the break address is enough, and
the length doesn't matter.
But I'll wait for your patch to see what
am I missing.
This particular bug seems to be
quite tricky again, to rush too much.
But I would really like to get all such
bugs fixed. They are not some corner
cases that can stay unnoticed for ages.
They show that the very core of the JIT
is not mature.

**Comment by stsp** [comment] 2020-06-14 15:07
> When trying to make Tree_InvalidateNodePage to not necessarily run on whole pages

Since you are at it, just a wish.
Please make it integrated with mpmap,
if possible! It is very annoying when you
have to do InvalidateNodePage(), then
resetpagemarks() then unprotect() and
hope all 3 to agree with each other.
And they do not!
InvalidateNodePage() crosses the page
boundaries, and resetpagemarks() has
no idea about that, so there would be
stalled code marks. With previous bugs,
also the opposite was possible: stalled
code nodes w/o code marks.
This is crap, really.
Yes, there are the attempts to unify that
at API level (e_invalidate(), m_unprotect()
and all that), but it will fail in all subtle ways
until the lookup and mpmap are properly
merged together.

I can even think of the "naive" merging
strategy: just remove avl and use the
large lookup arrays per mpmap. Yes,
memory waste, but who cares these
days about memory.
Of course the more sophisticated merging
strategies are possible, like probably
a small look-up trees per mpmap, or
something like that. I would guess that
we should stop crossing page boundaries
with code nodes, as this just gives all
the pain we have, for a very small
performance benefit.

So it would be good if some merging
is considered.

**Comment by bartoldeman** [comment] 2020-06-14 18:16
In the past there was the `NOJUMPS` define which was defined by default so the codegen would simply follow intra-page jumps. Then you could have a non-contiguous section of original code with key!=seqbase corresponding to a contiguous section of translated code, causing all sorts of headaches. I'm glad that is not there any more..

I don't think we can easily restrict to a single page, what to do with a single instruction that covers two pages then? Interprete it? Restricting to two pages is easier though.

Certainly the current complete separation between trees and mpmap is annoying. I'll try to think about this. The MpMap structures are really slapped on top to deal with SMC, and now they're used a bit more and it's too easy to get them out of sync.

I have one worry about the current no-overlap policy though -- it looks counterproductive. I looked at a trigger, the very first when booting FreeDOS:
```
block1
  00012d24: 8a3c              12ca:0084 mov  bh,[si]
  00012d26: 46                12ca:0086 inc  si
  00012d27: 10ff              12ca:0087 adc  bh,bh
  00012d29: c3                12ca:0089 ret

block2
  00012d1e: 11c9              12ca:007e adc  cx,cx
  00012d20: 00ff              12ca:0080 add  bh,bh
  00012d22: 7505              12ca:0082 jne  0089 ($+5)
```
what now happens is that when block2 exits with a jump to 12ca:0089 it will trigger the invalidation for the whole page. Now if just the node is invalidated it's still not perfect since you're throwing away a translation which is still correct, just entered in the middle.

So maybe it is after all better to allow overlaps and then make sure that `Tree_InvalidateNodePage` invalidates all nodes on the page, including overlapping ones...

**Comment by bartoldeman** [comment] 2020-06-14 19:26
Another idea is to jump into the middle of the block but at present that won't work because of e.g. the multi-push and multi-pop optimizations, you always have to start at the beginning.

My main issue with the current state without overlap is that we get code that's re-translated again and again, where e.g. in the above you get a block for 12d29 invalidating 12d24, then for 12d24 invalidating 12d29, etc etc.

**Comment by stsp** [comment] 2020-06-14 21:18
> follow intra-page jumps.

Oh, that's crazy indeed.
Thanks for info.

> My main issue with the current state without overlap is that we get code that's
> re-translated again and again,

Hmm, lets elaborate a bit.
This is not what I intended to code.

> where e.g. in the above you get a block for 12d29 invalidating 12d24

Yes, that's quite clear.
Say, you have node A with entry at a=12d24.
Then you jump to 12d29, node B gets created
with entry b=12d29. A is removed. So far so good.

> then for 12d24 invalidating 12d29

Why??
This was not intended in my patch.
The idea was that if someone jumped
to "a" again (a=12d24 as we noted),
then node C is created with smaller
length than A. C will only span from
a to b, then C will be linked with B.
So you have
12d24-->C-->12d29-->B
... and no A at all.
This is what I thought I coded up.
Have I actually done something else?

**Comment by stsp** [comment] 2020-06-14 21:35
> what to do with a single instruction that covers two pages then? Interprete it?

OK, good question. :)
Actually came to my mind too, just
much later than I wrote that.
Yes, if we don't know how to confine
things within a page, then we don't
know how to easily merge lookups
with mpmap...
So is this all sucker code just because
the page boundaries are crossed? :(

**Comment by bartoldeman** [comment] 2020-06-15 01:55
> This is what I thought I coded up.
> Have I actually done something else?

No you are correct, I was misled by the page protection, your scheme works as intended and we get nodes B and C. I'm still playing with the code but it looks correct once I decrease the invalidation range to just the node, except for spurious invalidations when CeS_LOCK is set. I'm still looking at that but the handling of that doesn't look entirely correct to me (as it's set during translation time but checked during run time)

**Comment by stsp** [comment] 2020-06-15 10:08
> CeS_LOCK is set. I'm still looking at that but the handling of that doesn't look entirely correct to me

I was very puzzled that removing "else"
keyword here:
https://github.com/dosemu2/dosemu2/blob/52db37384d83fc54c1dc481a69065a9cf222c2a0/src/base/emu-i386/simx86/interp.c#L411
fails tests.
Why not to handle CeS_TRAP when CeS_LOCK
is set, is still unclear to me.

**Comment by bartoldeman** [comment] 2020-06-15 12:16
> > CeS_LOCK is set. I'm still looking at that but the handling of that doesn't look entirely correct to me
> 
> I was very puzzled that removing "else"
> keyword here:
> 
> https://github.com/dosemu2/dosemu2/blob/52db37384d83fc54c1dc481a69065a9cf222c2a0/src/base/emu-i386/simx86/interp.c#L411
> 
> fails tests.
> Why not to handle CeS_TRAP when CeS_LOCK
> is set, is still unclear to me.

The purpose of CeS_LOCK is precisely in conjunction with the trap flag: if you do an instruction such as "pop ss", ints are disabled for one instruction so the trap flag is temporarily deactivated, and the tests check for that (see
```
                  /* when modifying SS, trace is not done on the next
                     instruction */
                  "movl %%ss, %%ecx\n"
                  "movl %%ecx, %%ss\n"
                 ...
```
in `test-i386.c`).

I think the mistake with CeS_LOCK is in this commit: 19ca91b890.
The loop really should not check CeS_LOCK but removing it gives me `ERROR: simx86: code nodes clashed at..` at various points so there is more debugging to do here.

**Comment by stsp** [comment] 2020-06-15 12:26
> The purpose of CeS_LOCK is precisely in conjunction with the trap flag:

OK but it seems to suppress also other
conditions, like signal etc - why is so?
And of course it obfuscates the original
intention.
If its a part of the core logic, then I think
HandleEmuSignals() is a wrong place
for it. It must be done elsewhere, after
the strict check that the PC have advanced
_after_ CeS_LOCK was cleared - only
then we can proceed with TF.
Also does this lock have something to
do with the lock prefix?

**Comment by bartoldeman** [comment] 2020-06-15 12:35
well it should suppress signals if possible, as "pop ss" and "mov ss" on a real CPU disables interrupts in general for one instruction.

It has nothing to do with the lock prefix.

**Comment by stsp** [comment] 2020-06-15 12:53
> well it should suppress signals if possible, as "pop ss" and "mov ss" on a real
> CPU disables interrupts in general for one instruction.

Suppressing signals is actually just a
hack that happens to lead to somewhat
correct results. If we look at VTx, it simply
has the additional state bits that disable
interrupts, besides the IF flag. There is
also a preemption timer that causes the
vmexit, and it doesn't care about any
interrupt hold-offs: they are recorded
into the state struct, and the exit proceeds.
I think disabling signal exits and putting
CeS_LOCK interaction with TF into
HandleEmuSignals() w/o properly checking
that PC have advanced, is a very fragile
approach.

**Comment by stsp** [comment] 2020-06-15 14:52
> If we look at VTx, it simply

And because we use KVM, I highly
suspect we do not handle that correctly.
I think KVM will exit no matter if the
interrupt hold-off is active, and we only
check IF. Or is there some magic?

**Comment by bartoldeman** [comment] 2020-06-15 15:47
KVM handles it internally as far as I know, the tests with TF and mov ss just work without any special effort. I've only had issues with the interrupt shadow when using real-mode (in my early KVM patches that did not use vm86) in combination with STI but not with MOV/POP SS (commit e370fbe8a3f)

**Comment by stsp** [comment] 2020-06-20 20:01
This one is not fixed by SINGLEBLOCK
(but is - with SINGLESTEP) so I think this
have nothing to do with any BreakNode
problems, as BreakNode shouldn't happen
in SINGLEBLOCK I think.

**Comment by stsp** [comment] 2020-06-20 20:03
But logging shows BreakNode is used
even in SINGLEBLOCK... Is it intentional?

**Comment by stsp** [comment] 2020-06-20 21:35
Why BreakNode() checks if the
write was forward, and hit the same
node? Does it matter was it forward
or backward, if we unprotect the
entire page?

**Comment by stsp** [comment] 2020-06-20 23:42
I did an experiment.
Disabled node linker.
Made CALLd to always produce the separate
node (of 3 bytes) and backed up these 3
bytes in a node. Before re-executing the
node, I did memcmp (actually for all nodes,
not only for CALLd).
And no, no unnoticed writes!
The data matches, not corrupted.
So the miscompilation of the CALLd seems
to be the only possibility now...

**Closed** 2020-06-21 00:12 UTC
Labels: bug

**Comment by stsp** [comment] 2020-06-21 00:14
Should now be fixed.
Indeed, a miscompilation of some kind...
We calculate address wrap-around in
interp and not in a compiled code.
But its a rare case, possibly not worth
changing the compilation templates.

**Comment by stsp** [comment] 2020-06-21 00:18
All WP6 problems are addressed, it seems.

**Comment by bartoldeman** [comment] 2020-06-21 00:33
yes I was just thinking about CS when you mentioned CALLd. It's something that QEMU checks too when looking for a translated block, see e.g. here http://people.redhat.com/pbonzini/qemu-test-doc/_build/html/topics/Translator-Internals.html under "Direct Block Chaining"

The trouble with call (and not jmp) is that it pushes an IP that is computed at compile time as you noticed. The alternative is to use P2+pskip as the argument and then the generated code needs to subtract LONG_CS and mask for 16-bit. It's not hard to do but indeed quite rare to have a mismatch.

**Comment by stsp** [comment] 2020-06-21 00:40
> The trouble with call (and not jmp) is that it pushes an IP

Not sure I understand,
It pushes _current_ IP.
The problem should be with the
wrap of the target addr.

**Comment by stsp** [comment] 2020-06-21 00:41
Ah, yes, pushed IP can also wrap.
So call have 2 problems and jmp have 1.

**Comment by stsp** [comment] 2020-06-21 00:42
We need to fix BreakNode though.
I think this forward check there is not good.

**Comment by bartoldeman** [comment] 2020-06-21 01:44
It's not just wrapping (which is indeed another issue).
suppose we compile `call xxxx` at `1200:0100`, it will push an ip of `0103`. Then if that same code is executed at `1000:2100`, it still pushes `0103` but should push `2103`.

but indeed the wrapping indeed also affects jmp as you say.

For breaknode the idea is that if it we're interrupting a piece of code that is no longer valid because of the self-write. It could be interrupted unconditionally or one could think that if it's a backward write then the rest of the current translated block still corresponds to the original code and can be executed until the end. But I think you're right: even for a backwards right executing the remainder of the block is not safe since the underlying code is now unprotected so that a second SMC hit is no longer detected!

So it looks like 221914a should be reverted since 12cb55498 was the proper fix... (not that with the revert enpc and hence addr is no longer used in BreakNode()...)

**Comment by bartoldeman** [comment] 2020-06-21 03:03
Looking at it again, calculating IP/EIP in compiled code is easy but the wrapping messes everything up as the NodeLinker relies on constant jump targets, so your fix is the only one that makes sense, we have to recompile if the jump targets change.

**Comment by stsp** [comment] 2020-06-21 11:15
> So it looks like 221914a should be reverted

Done.

> Looking at it again, calculating IP/EIP in compiled code is easy

Indeed, something like `PUSH((TheCPU.eip + dnpc + pskip) & 0xffff);`
But for what...

> so your fix is the only one that makes sense

But is it complete?
Can node linker ever link nodes that change CS?
If so, it should also check for CS match.
