### ISSUE TITLE
WSL Ubuntu: "cpu exception in dosemu code outside of VM86()!"

### ISSUE THREAD

**Issue by emendelson** [dosemu2/dosemu2#1987] opened 2023-04-07 17:56 UTC
**Describe the bug**
Running current builds of dosemu2 in WSL Ubuntu Jammy, produces this error message:

```
ERROR: cpu exception in dosemu code outside of VM86()!
Floating point exception (Floating-point divide by zero [0x7f10ef264751])
```
The hex number differs on different systems, but the rest of the message is the same.

**To Reproduce**

Under WSL Ubuntu, enter `dosemu`.

**Attach the log**
Here's the log from `D9+g` - though I don't know if that's the right command here.
[boot.log](https://github.com/dosemu2/dosemu2/files/11180565/boot.log)

**A regression?**
This didn't happen three months ago, but I can't say when it began.

**Additional info**
No customizations; there's no `dosemurc` on the new system that I'm reporting about.

**Comment by stsp** [comment] 2023-04-07 18:14
Unfortunately the logging was disabled. :(
Please produce the new log tomorrow,
when the new build is available.
Thanks!

**Comment by emendelson** [comment] 2023-04-07 20:49
Will do. Presumably the log should be a lot bigger??

**Comment by stsp** [comment] 2023-04-08 09:16
Not multi-giga bigger.
But at the range of 100Kb it should
be the hint that the patch worked.

**Comment by emendelson** [comment] 2023-04-08 17:49
Patch worked; boot log attached (-D9+g, if that's right...)

[boot.log](https://github.com/dosemu2/dosemu2/files/11183810/boot.log)

EDIT: Maybe the bug report template could explain exactly which -D options to use? I only use -D9+g because I found it in some of these discussions. It would be good to know exactly what is most useful.

**Comment by stsp** [comment] 2023-04-08 17:57
You need to install the dbgsym
package and re-do the log.

**Comment by stsp** [comment] 2023-04-08 18:02
> EDIT: Maybe the bug report template could explain exactly which -D options to use?

Done.
It now asks for the log unless you
report a dosemu2 crash.

**Comment by emendelson** [comment] 2023-04-08 23:55
> You need to install the dbgsym
> package and re-do the log.

How do I install the dbgsym package? I tried `sudo apt install dosemu2-dbgsym` with no luck. I've searched this site, but can't find any detailed instructions. If you can provide step-by-step instructions, with the full commands, that would be useful, because I've never done anything like this before.

EDIT: I found a post that says the symbols are on the PPA page, but I can't find them here: 

https://launchpad.net/~dosemu2/+archive/ubuntu/ppa

Maybe I'm looking at the wrong page?

**Comment by stsp** [comment] 2023-04-09 06:24
You can install it by hands from here:

https://code.launchpad.net/~dosemu2/+archive/ubuntu/ppa/+files/dosemu2-dbgsym_2.0~pre9-8006-f8558eb8a+202304081203~ubuntu23.04.1_amd64.ddeb

For another ubuntu version, browse here:
https://code.launchpad.net/~dosemu2/+archive/ubuntu/ppa/+packages

Maybe @skitt can tell us how to install
those with apt-get, I have no idea. :)

**Comment by andrewbird** [comment] 2023-04-09 10:49
There may be a better way, but for me adding `main/debug` to the end of the active line in the dosemu repo config file
~~~
vi /etc/apt/sources.list.d/dosemu2-ubuntu-ppa-jammy.list
~~~
to look like
~~~
deb https://ppa.launchpadcontent.net/dosemu2/ppa/ubuntu/ jammy main main/debug
~~~

then `apt update; apt install fdpp-dbgsym dosemu2-dbgsym` does it for me

**Comment by emendelson** [comment] 2023-04-09 14:41
@andrewbird - That got the job done perfectly. Thank you.

@stsp - Here's the log, with I hope the stuff you wanted:

[boot.log](https://github.com/dosemu2/dosemu2/files/11185680/boot.log)

EDIT: And I don't see any debug symbols on the page that you linked to: https://code.launchpad.net/~dosemu2/+archive/ubuntu/ppa/+packages

**Comment by stsp** [comment] 2023-04-09 15:47
Please install also dbgsyms for:
libsdl2
libglx-mesa0
libgl1-mesa-dri

**Comment by emendelson** [comment] 2023-04-09 17:37
I've spent the past hour trying to figure out how to do this. None of the solutions I've found online let me install those dbgsyms. I'll keep trying. @andrewbird - if you have any inspirations, I'll be grateful.

**Comment by stsp** [comment] 2023-04-09 17:49
I do this time. :)
https://ubuntu.com/server/docs/service-debuginfod
It appears there is no need to install
any packages.
Just add this to ~/.gdbinit:
`set debuginfod enabled on`
And type this before starting dosemu2:
`export DEBUGINFOD_URLS="https://debuginfod.ubuntu.com"`

Now after the crash you'll need to wait
a couple of minutes for it to download
things on his own.

**Comment by emendelson** [comment] 2023-04-09 20:12
That was easy! As you said, after the crash, I had to wait a while until the prompt returned.

Here's the log:
[boot.log](https://github.com/dosemu2/dosemu2/files/11186229/boot.log)

**Comment by stsp** [comment] 2023-04-10 08:26
This didn't do the trick.
It downloaded some debug info,
but obviously not all of it.
I added the `--readnow` flag now,
which may or may not force gdb
to read all needed debug info.

While you wait for a new packages,
please follow this guide:
https://wiki.ubuntu.com/Debug%20Symbol%20Packages
It describes the process to enable
the dbgsym packages. After doing
the needed mods to /etc/apt*, you'll
need to run
`find-dbgsym-packages /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so`
This will go silent for an hour, but be
patient, it didn't hang just yet. :)
At the end it will generate you the
meta-package, eg
`/tmp/dbgsym-pkgs-for-swrastdriso_2023.04.10T13.12.49+dg0.88ubuntu1_all.deb`
on which you can use `apt install`,
and it will install the needed debuginfo
for that library.
Then repeat that for
`/lib/x86_64-linux-gnu/libGLX_mesa.so.0`
and
`/lib/x86_64-linux-gnu/libSDL2-2.0.so.0`

Don't ask me who invented such procedure. :)
Obviously ubuntu is against any debugging,
but we'll manage.

**Comment by stsp** [comment] 2023-04-10 08:38
Actually the meta-package was likely
generated  because I specified --deb.
There are other options, like --install,
that may suit better. Experimenting with
the tool that stays silent for an hour, is
not the best time-spending. :)

**Comment by stsp** [comment] 2023-04-10 09:40
Hi Andrew, once again the debug info
wasn't recorded on CI:
https://github.com/dosemu2/dosemu2/actions/runs/4655839017/jobs/8238875551
But this time it was started to collect.
Can there be some timeout that prevents
the debug info from getting fully collected?

**Comment by emendelson** [comment] 2023-04-10 14:30
OK, I'm confused. Should I perform the steps you outline here, starting with:

```While you wait for a new packages,
please follow this guide:
https://wiki.ubuntu.com/Debug%20Symbol%20Packages
It describes the process to enable
the dbgsym packages. 
```
or will the new versions of dosemu2 and dosemu2-dbgsym be enough, without going through the hour-long wait?

**Comment by stsp** [comment] 2023-04-10 15:14
I have no idea if the change helps, so
you can do both inparallel. Waiting
parallelizes exceptionally well. :)

**Comment by emendelson** [comment] 2023-04-10 16:05
Well, in the long list of instructions I got as far as

```
you'll need to run
find-dbgsym-packages /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
```
I tried the command with and without `sudo` and got this:

```
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libstdc++.so.6
W: Cannot find debug package for /lib/x86_64-linux-gnu/libstdc++.so.6 (f57e02bfadacc0c923c82457d5e18e1830b5faea)
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libdrm.so.2
W: Cannot find debug package for /lib/x86_64-linux-gnu/libdrm.so.2 (9c7cb19295d20e515902cb0710326a0b8d6394c8)
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libdrm_amdgpu.so.1
W: Cannot find debug package for /lib/x86_64-linux-gnu/libdrm_amdgpu.so.1 (55735af4f6152d6148117c98fa6db08ed1d34fe5)
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libdrm_radeon.so.1
W: Cannot find debug package for /lib/x86_64-linux-gnu/libdrm_radeon.so.1 (2c199d459f832a915a700e1a9234cf9e14656889)
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libxml2.so.2
W: Cannot find debug package for /lib/x86_64-linux-gnu/libxml2.so.2 (2025ebcf5a6f422d82bdf345647c746def8ecaa2)
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libicuuc.so.70
W: Cannot find debug package for /lib/x86_64-linux-gnu/libicuuc.so.70 (bef3ff1d70aadd68aab07d858a759360c8b919ae)
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libLLVM-15.so.1
W: Cannot find debug package for /lib/x86_64-linux-gnu/libLLVM-15.so.1 (ddf13b5e267795aec7b034aa9c7b088fcb2ccd88)
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libicudata.so.70
W: Cannot find debug package for /lib/x86_64-linux-gnu/libicudata.so.70 (b1c2496dd0543023c7a19c961bb7f3abc818f465)
dpkg-query: no path found matching pattern /lib/x86_64-linux-gnu/libdrm_nouveau.so.2
W: Cannot find debug package for /lib/x86_64-linux-gnu/libdrm_nouveau.so.2 (717e881b4ee3b0bc2344b0f63c4fc10c84263f13)
libbsd0-dbgsym libedit2-dbgsym libelf1-dbgsym libexpat1-dbgsym libffi8-dbgsym libgcc-s1-dbgsym libgl1-mesa-dri-dbgsym libglapi-mesa-dbgsym liblzma5-dbgsym libmd0-dbgsym libsensors5-dbgsym libtinfo6-dbgsym libxau6-dbgsym libxcb-dri3-0-dbgsym libxcb1-dbgsym libxdmcp6-dbg libzstd1-dbgsym zlib1g-dbgsym
```
I also tried using the script linked at the foot of the instructions page, but couldn't get any output from it, possibly because I don't know how to customize the syntax. 

Anyway, here's another boot.log in case it's more useful:

[boot.log](https://github.com/dosemu2/dosemu2/files/11191870/boot.log)

**Comment by stsp** [comment] 2023-04-10 16:17
So it gave you the list of packages to
install. You can install them with apt-get
or use --install opt of the command itself.

**Comment by emendelson** [comment] 2023-04-10 18:12
So I tried the --install option and got this result:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libexpat1-dbgsym : Depends: libexpat1 (= 2.4.7-1) but 2.4.7-1ubuntu0.2 is to be installed
 libgcc-s1-dbgsym : Depends: libgcc-s1 (= 12-20220319-1ubuntu1) but 12.1.0-2ubuntu1~22.04 is to be installed
 zlib1g-dbgsym : Depends: zlib1g (= 1:1.2.11.dfsg-2ubuntu9) but 1:1.2.11.dfsg-2ubuntu9.2 is to be installed
E: Unable to correct problems, you have held broken packages.
```
This is completely new territory for me, so if you can figure out how to fix it, please tell me the full, exact commands that I need to enter. I tried installing libexpat1, libgcc-s1, and zlib1g, but I was told I already had the newest version.

**Comment by skitt** [comment] 2023-04-10 18:17
Can you show the output of `apt policy`?

**Comment by emendelson** [comment] 2023-04-10 18:18
> Can you show the output of `apt policy`?

[output.txt](https://github.com/dosemu2/dosemu2/files/11192826/output.txt)

**Comment by skitt** [comment] 2023-04-10 18:26
Thanks, that looks fine — I wanted to check whether your repositories were set up correctly. I’m afraid I’m not familiar enough with the `dbgsym` repositories in Ubuntu to figure out what’s going wrong on your system...

**Comment by emendelson** [comment] 2023-04-10 18:27
This may not be worth any further trouble, as I may be the only person in the universe who is trying to run dosemu under WSL.

**Comment by stsp** [comment] 2023-04-10 18:56
You can still try other forums, like
askubuntu.com.

**Comment by emendelson** [comment] 2023-04-10 19:40
I'll do that and report back.

**Comment by bartoldeman** [comment] 2023-04-11 02:00
I tried compiling dosemu2 in WSL2 (Debian 11, not Ubuntu though), and it works fine.

There seems to be some issue in the Ubuntu Jammy version of swrast_dri.so, which may be innocent as without trapping of floating-point exceptions you get NaNs and Infinities, but if those aren't used down the road, it's not an issue.

We should perhaps disable the
```feenableexcept(FE_DIVBYZERO | FE_OVERFLOW);```
(src/base/emu-i386/cpu.c::297) for non-debug builds?

**Comment by stsp** [comment] 2023-04-11 05:17
Maybe if it helps... We dont even know if
it does. I'd prefer not, it used to catch bugs
before, and now ubuntu just fscked the
debuginfo support.
But if someone can create and test the patch...

**Comment by stsp** [comment] 2023-04-11 07:56
In a mean time I confirmed my theory
that CI can easily timeout w/o letting
dosemu2 to collect gdb logs.
If I do this:
```
diff --git a/src/arch/linux/async/debug.c b/src/arch/linux/async/debug.c
index 6433c69df..a0b79c6f3 100644
--- a/src/arch/linux/async/debug.c
+++ b/src/arch/linux/async/debug.c
@@ -34,7 +34,7 @@ static int start_gdb(pid_t dosemu_pid)
 
   printf("Debug info:\n");
   fflush(stdout);
-
+sleep(20);
   ret = asprintf(&buf, "gdb --readnow %s", dosemu_proc_self_exe);
   assert(ret != -1);
```

and then do `killall -SEGV dosemu.bin`
while running any test, then the full log
is never there.
Andrew, how should we deal with that?
I realize that the small timeout for tests
is needed to not overload the CI. But
would it be possible to parse the logs
before killing the process on timeout,
and if there are the signs of a debug-info
being collected, then use a much, much
larger timeout?

**Comment by andrewbird** [comment] 2023-04-11 12:11
I made a hopeful patch that may help #1989 , see if you can trigger again please?

**Comment by andrewbird** [comment] 2023-04-11 12:26
Actually, it looks like my CI run is failing, and waiting, so we may see the results!

**Comment by andrewbird** [comment] 2023-04-11 12:47
Seems to have caught it, see https://github.com/andrewbird/dosemu2/actions/runs/4667328483/jobs/8262994565

**Comment by stsp** [comment] 2023-04-11 13:36
Thanks.
That's likely a regression of
https://github.com/dosemu2/fdpp/commit/51bfc5fb670ba0e739ce48a8dfbc7e29a9b81fa6
I'll think how to fix that.
I unfortunately have forgot most of
the fdpp compiler internals, and that
one seems like a core problem.

**Comment by bartoldeman** [comment] 2023-04-11 18:25
@emendelson

Can you try
export LIBGL_ALWAYS_SOFTWARE=yes
dosemu
or
LIBGL_ALWAYS_SOFTWARE=yes dosemu

 It's not quite clear to me yet why SDL is involving Mesa since dosemu2 doesn't use hardware acceleration by default (unless you set `$_SDL_hwrend=(on)`.

In my Debian 11 compilation it doesn't even load libGL, which is why it doesn't crash for me there, but I can see it now with Ubuntu Jammy on WSL2. The crash comes from Mesa's Direct 3D DRI driver (src/gallium/drivers/d3d12/d3d12_screen.cpp). 

LIBGL_ALWAYS_SOFTWARE disables D3D12, and force Mesa (not dosemu2 itself) to use pure software rendering.

**Comment by stsp** [comment] 2023-04-11 18:31
Its likely so because of b7c2edd89
I've been told in sdl bugzilla that wayland
is not going to be supported with a pure
sw rendering.

**Comment by bartoldeman** [comment] 2023-04-11 20:20
> Its likely so because of [b7c2edd](https://github.com/dosemu2/dosemu2/commit/b7c2edd89e20c5c6037289c36e959360df5f8add) I've been told in sdl bugzilla that wayland is not going to be supported with a pure sw rendering.

Correct, reverting that makes the issue go away. I'll try and make a small reproducer for Mesa as well, so the bug can be fixed on their side.

I think LIBGL_ALWAYS_SOFTWARE=yes is a good workaround for now though (not sure if we should set that envvar automatically though)

**Comment by stsp** [comment] 2023-04-11 20:26
If we set it automatically, it will likely
break wayland again? Can check that
tomorrow.

**Comment by emendelson** [comment] 2023-04-12 01:03
@bartoldeman 

As you said: `LIBGL_ALWAYS_SOFTWARE=yes dosemu` lets dosemu launch under Ubuntu jammy.

I get this error message on launch:
```
ERROR: alsa_midi:virtual (ALSA err 2): open /dev/snd/seq failed: No such file or directory
snd-virmidi module not loaded or device "virtual" not configured
see "amidi -l" for the list of midi devices
```
but I don't know (you will know) whether that's related to this issue, or whether I need to install something that I haven't installed.

**Comment by bartoldeman** [comment] 2023-04-12 01:13
> but I don't know (you will know) whether that's related to this issue, or whether I need to install something that I haven't installed.

No, it's a limitation of WSL, it doesn't provide this sound support. You can ignore the warning (if you don't care about the missing music/sounds in dosemu2).

If you set
$_sound=(off)
explicitly in ~/.dosemurc, the message goes away.

**Comment by bartoldeman** [comment] 2023-04-12 02:34
Submitted Mesa issue:
https://gitlab.freedesktop.org/mesa/mesa/-/issues/8818

**Comment by stsp** [comment] 2023-04-12 09:26
Just for completeness:
LIBGL_ALWAYS_SOFTWARE=yes
doesn't seem to break wayland.
Although I don't know how to check
if the setting actually worked.

**Comment by bartoldeman** [comment] 2023-04-12 13:43
I think in this case a more straightforward workaround is to move the FPU exception enable to just past device_init(): split off `fpu_setup()` from `cpu_setup()`? I tested that and it works.

**Comment by stsp** [comment] 2023-04-12 13:46
So are you sure this mesa bug is
not fatal and everything works as
expected after just suppressing the
SIGFPE?
If so - lets do that.
But I'd rather wait for a couple of
days, maybe there will be an answer
in the ticket you created...

**Comment by stsp** [comment] 2023-04-13 08:22
Actually, Bart, can we just instead mask
an fpu exception in a sighandler, and return
after dumping and logging?

**Comment by bartoldeman** [comment] 2023-04-13 13:08
> Actually, Bart, can we just instead mask an fpu exception in a sighandler, and return after dumping and logging?

Not sure how to do that without some instruction emulation (or at least advancing eip/rip...)
Of course you can regularly check for raised masked FP exceptions (using e.g. `fetestexcept()`), but then you don't have the same info.

I think it's still simplest just to delay the unmasking a little until after device_init().

I had a look what this all means for Mesa, it seems to be related to a multiplier for GL_TIMESTAMP functionality, which isn't very well supported across OpenGL implementations in the first place, and SDL doesn't use it as far as I can see. So if the multiplier is `inf` (infinity), then converted to uint64_t (which happens to be 0 using the static_cast conversion using `g++` ), I think you get timestamps of 0 for OpenGL operations. Which are of course wrong but given the obscurity of GL_TIMESTAMP and the fact that most software runs with FP exceptions masked, I'm not surprised we are the first ones to notice.

**Comment by stsp** [comment] 2023-04-13 14:24
> Not sure how to do that without some instruction emulation (or at least advancing eip/rip...)

Could you please clarify that?
If we use feenableexcept() to mask
the division by zero, then why do we
care about eip? The exception won't
be re-raised because of a mask, or
what am I missing?

**Comment by bartoldeman** [comment] 2023-04-13 15:38
Calling feenableexcept() in the signal handler won't unmask exceptions (outside the signal handler) since it'll restore the FPU control word and mxcsr (SSE) upon sigreturn. We'd need to change them on the signal stack... Easier than adjusting eip, but still architecture (and SSE/x87) dependent.

**Comment by stsp** [comment] 2023-04-13 15:47
I think we can do that via scp->fpstate
if the sigreturn's fpstate is compatible with
glibc's fpstate. In that case we probably
can mask an exception and then use
`makecontext`, and then replace an
scp->fpstate with that.
Is it an option, or are they incompatible?

**Comment by bartoldeman** [comment] 2023-04-13 19:33
Too much work for me to workaround an issue in somebody else's code...
Just coded #1991, temp disable of fp division by zero, but we still get all FP exceptions in dosemu2 itself.

**Comment by stsp** [comment] 2023-04-13 19:42
Good idea.

**Comment by stsp** [comment] 2023-04-13 21:10
Bart fixed the problem, so please re-try
tomorrow.

**Closed as completed** 2023-04-13 21:09 UTC

**Comment by stsp** [comment] 2023-04-13 21:10
I mean, Bart applied a work-around, not
fixed the problem. :)

**Comment by emendelson** [comment] 2023-04-15 12:15
The work-around works. Well done, and thank you for sorting out that special-case complication.
