### ISSUE TITLE
Use SDL_ttf for font rendering

### ISSUE THREAD

**Issue by fhanzlik** [dosemu2/dosemu2#18] opened 2015-01-27 02:01 UTC
It seems as '$_X_winsize' is now accepted only with built-in font. It would be useful, when it would work also when $_X_font specifies scallable fonts, because then should be one character dimension determinable. My, maybe little naive, idea:
$_X_winsize = "1400,1024" => (80x25 text mode):
 1400 / 80=17.5 =~ 17 (character width in pixels)
 1024 / 25=40.96 =~ 40 (character height in pixels)

Now is possible tune window size by setting Pixel_Size/Point_Size/Resolution_X/Resolution_Y in XLFD $_X_font specification (e.g. instead
$_X_font = "-misc-freemono-medium-r-normal--0-0-0-0-c-0-iso10646-1"
set
$_X_font = "-misc-freemono-medium-r-normal--47-0-70-0-c-0-iso10646-1"
), but with $_X_winsize this should be much more clearly.

**Comment by stsp** [comment] 2015-09-17 13:42
So for this we'd need SDL_ttf.
I don't think trying to find a best-match bitmap
font is worth the troubles.

**Comment by stsp** [comment] 2015-09-17 13:44
And if we have SDL by default, then at least
people could you AA. I'm going to make SDL
by default.

**Comment by stsp** [comment] 2019-04-05 15:20
I'll give 150$ to anyone who implements this.

**Comment by stuaxo** [comment] 2019-04-05 18:01
It could do something like:

If the character is using the default font, then render using the nearest bitmapped font.

If characters have been changed (e.g. on VGA text mode) then the current scaling method would be used.

**Comment by stsp** [comment] 2019-04-06 00:17
Using the X fonts in sdl mode
is a big hack. It should go away.
In sdl mode we should either use
ttf or built-in vga font.
I am not sure what you mean by
character changed.

**Comment by stuaxo** [comment] 2019-04-06 10:29
In VGA you can customise the text mode characters on the fly.

There's a mode where the high bit (blink) switches between one of two fonts.

I built a mostly functioning TUI font editor based on this in the late 90s.

I thought it worked in Dosemu, but I might be confusing it with Dosbox?

I can try and find it out and test, I would release it embarrassing TurboPascal code and all, but some bits like file dialogs are not fully working.

The font change code was taken from an example in the book PC Intern

**Comment by stuaxo** [comment] 2019-04-06 10:35
Here is (vb) example showing changing fonts

https://microsoft.public.vb.dos.narkive.com/d4MUjeRE/changing-screen-raster-font-from-vb

**Comment by stsp** [comment] 2019-04-07 16:47
In X font mode the run-time vga font
changing is not supported. And if you
try to detect the change and fall back
to vga font, then there will be no X
font at all, as most people load the
national charset, so the vga font is
almost always modified.

**Comment by stuaxo** [comment] 2019-04-07 19:57
Changing national characterset is something I haven't played with, I'm curious to see what the differences are.

Should I consult freedos docs on how to do this?  I've got a vague memory of cpi being involved?

**Comment by stsp** [comment] 2019-04-07 23:25
Yes, or you can load the prog like
keyrus.com, that also installs the font.
This is just outside of the scope of
this ticket.
All that is needed here is to replace
X font rendering with SDL_ttf for SDL
mode.

**Comment by andrewbird** [comment] 2019-05-27 22:15
I started work on sdl_ttf stuff. I have the first screenshot of sdl_ttf window with the font I mentioned [here](https://int10h.org/blog/2018/05/flexi-ibm-vga-scalable-truetype-font/)
![sdl_ttf](https://user-images.githubusercontent.com/220835/58440855-22b22380-80d5-11e9-9def-35494e8c4567.png)

Still lots of work to do (cursor, keyboard) etc

**Comment by stsp** [comment] 2019-05-28 01:24
Wow, looks great!
That functionality was really missed.
I wonder why do you mention keyboard
though. Or are you aiming for the
bigger goal of having no dlopen() of
an X plugin from sdl?

**Comment by andrewbird** [comment] 2019-05-28 08:23
Yes I removed dlopen of Xplugin so lost the XKB stuff. As discussed in #87 the SDL keyboard may not be enough. I do wonder about Wayland though

##### TODO
- [ ] cursor
- [ ] I18N keyboard
- [ ] I18M display
- [x] colours
- [ ] resize

It's really rough work at the moment and will need to be tidied and squashed.

**Comment by stsp** [comment] 2019-05-28 09:28
How about just implementing the
rendering first, the rest next?
Otherwise there is a fear that nothing
will be done. :)

**Comment by andrewbird** [comment] 2019-05-28 09:36
That's pretty much what I'm doing, the sdl keyboard handling was there already. I figure that if I need to go back to XKB then I should move that code out from X plugin into somewhere common so that it can be statically linked into each plugin.

**Comment by stsp** [comment] 2019-05-28 10:02
But why does this all matter if you
only add the ttf rendering? Isnt it
possible to do w/o any keyboard
changes?

**Comment by andrewbird** [comment] 2019-05-28 10:22
it doesn't except that I want to remove the dlopen of X plugin. Let's see how far I get, I can always revert to something like you suggest.

**Comment by stsp** [comment] 2019-05-28 10:27
I am not saying to revert.
Just publish the ttf part as a PR and
do anything else you like. :)
Anyway, I can wait.

**Comment by andrewbird** [comment] 2019-05-28 14:04
I meant revert in the literal sense rather than in git, that my goal was to avoid the dlopen, and of course that may not be easy. I'll have another look later, I have non dosemu stuff to do today :smile:

**Comment by andrewbird** [comment] 2019-05-28 21:15
What's this function used for, how can I trigger its use?
```C
/*                                                                              
 * Draw a horizontal line (for text modes)                                      
 * The attribute is the VGA color/mono text attribute.                          
 */                                                                             
static void X_draw_line(void *opaque, int x, int y, int len)                    
```

**Comment by stsp** [comment] 2019-05-28 21:35
Underlined MDA text, I suppose.
https://en.wikipedia.org/wiki/VGA-compatible_text_mode#Underline

**Comment by andrewbird** [comment] 2019-05-28 21:59
Okay, I'll leave that function for now.

Regarding window resize, how should that work? At the moment if I grab the window frame and drag it to a larger size scaling occurs, with the corresponding loss of text clarity. Whereas if I load the font with a larger point size the text looks beautiful see below:
![ttf-40-point](https://user-images.githubusercontent.com/220835/58515192-ff9e7700-819b-11e9-9784-3aebe8a09925.png)
Currently the aspect ratio of the window is not maintained, so how should that be handled?

**Comment by andrewbird** [comment] 2019-05-28 22:07
I pushed my work in progress so you can have a play with it https://github.com/andrewbird/dosemu2/tree/sdlttf-01

**Comment by stsp** [comment] 2019-05-28 23:04
I suppose if we do not maintain the aspect ratio
and someone stretches the window in just one
dimension, then scaling is the only possibility.
But aspect ratio is a default setting, and if it is
maintained, we need to change the font size.
How to do this with sdl_ttf most efficiently is what
I don't know. But we need to find this out or the
whole idea is useless, right?

OK, let's brain-storm.
What if we load the font of the maximum size
needed for the full-screen resolution (or some fixed
HD resolution), and then only down-scale? Not sure
if this will work right, but quite easy to check?

**Comment by stsp** [comment] 2019-05-28 23:29
Would the dumb solution be possible?
On every resize event, calculate the needed
font size and reload the font?

**Comment by andrewbird** [comment] 2019-05-29 08:18
Sorry, I went to bed!
> Would the dumb solution be possible?
On every resize event, calculate the needed
font size and reload the font?

This seems like the better solution. I also figure that resizing a Linux terminal must go through a similar, but not identical solution. On my Lxterminal with LXDE and I resize by dragging, the window enlarges by visible steps as its size changes to be a multiple of the font size and rows/columns inside. On a file manager the resize is smooth. I wonder if that stepping is forced by the application or if it's a feature of the window manager?

**Comment by andrewbird** [comment] 2019-05-29 13:24
I coded something up for resizing window in text mode by choosing new font point size. it seems to work quite well, let me know what you think?

**Comment by stsp** [comment] 2019-05-29 14:26
Not that I like this approach, but I googled a lot
and found nothing better.
So if it works... :)

**Comment by andrewbird** [comment] 2019-05-29 18:42
##### resize
I'm happy with the windowed resizing, but not keen on the fullscreen representation as it has bars right and left to account for 4:3 aspect ratio of VGA on my widescreen monitor. Not sure what the 'correct' fix is here:
  a) resize font for Y axis and then scale X & Y to fit screen
  b) ensure the bars are black not some random colour and respect the 4:3 aspect ratio

##### keyboard
Yep I need to re-add the XKB code or lose I18N keyboards. Would like to split out the common code from `keyb_X_keycode` to be compile time linkable.

**Comment by stsp** [comment] 2019-05-29 20:42
> Not sure what the 'correct' fix is here:

Just ignore aspect_43 in the custom-font text-mode.

**Comment by andrewbird** [comment] 2019-05-29 21:04
I think the aspect ratio in this instance is a function of the width & height of the font I'm using. The one I have here is 4:3 which is supposed to be true to VGA,  but there is an alternative available.

**Comment by stsp** [comment] 2019-05-29 21:05
Yes, that's what I mean.
If the fixed aspect is requested, just use
the font aspect. In gfx mode we can honor 4:3

**Comment by stsp** [comment] 2019-05-30 00:06
> Yep I need to re-add the XKB code or lose I18N keyboards.

This is almost a bug actually.
All we need is to query the current keyboard
layout. Then we could write the code that would
produce almost the same result as an xkb code
now does. But it seems SDL lacks layout query API.

**Comment by andrewbird** [comment] 2019-05-30 00:49
Perhaps the future is XKB for both X and Wayland?
https://unix.stackexchange.com/questions/309580/does-wayland-use-xkb-for-keyboard-layouts

**Comment by stsp** [comment] 2019-05-30 08:48
In sdl? :(

**Comment by andrewbird** [comment] 2019-05-30 10:16
> Perhaps the future is XKB for both X and Wayland?

Ignore that! I now believe XKB is only for X compatibility in Wayland and it looks like the proper interface is 'wl_keyboard'.

https://people.freedesktop.org/~whot/wayland-doxygen/wayland/Client/group__iface__wl__keyboard.html
https://people.freedesktop.org/~whot/wayland-doxygen/wayland/Client/structwl__keyboard__listener.html

I now think this may be too early to think about Wayland. I think Fedora 30 has it, but few other distros do. Certainly my Lubuntu 18.04 doesn't have Wayland enabled in SDL so I can't test anything anyway.

Are you okay with my pulling out XKB keyboard detection from X plugin and putting it in a static library somewhere? If so where should it live in the dosemu source? I'll do this is a different branch to my sdlttf experiments.

**Comment by stsp** [comment] 2019-05-30 10:44
Yeah, that's fine.
You can leave it where it is, just tweak
the makefile so that this code go into a static
lib, and the rest of X code in a .so plugin.

**Comment by stsp** [comment] 2019-06-03 22:52
Hi Andrew, I've prototyped the i18n keyboard code for you.
Well, in fact I simply removed the old code - this was all that
is needed. Seems to work.
Please give it some testing and I'll merge.

**Comment by andrewbird** [comment] 2019-06-03 22:58
Thanks I was getting bogged down with this, I'll give it a try tomorrow.

**Comment by andrewbird** [comment] 2019-06-04 09:05
Mmm, I don't seem to be able to switch keyboard mappings, I always get uk, fr-latin1 even when my active keymap is fr or de.

~~~
$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     gb,fr,de
variant:    ,,
options:    grp:ctrl_shift_toggle
~~~

This is much the scenario that we discussed at length in #43.

I also note that X plugin is still doing the auto detection.
~~~
$ grep -i detect test.log
CONF: detected layout is "uk"
CONF: detected alternate layout: fr-latin1
~~~
~~~
$ git grep 'detected layout'
src/plugin/X/X_keymaps.c:  c_printf("CONF: detected layout is \"%s\"\n", config.keytable->name);
~~~

One further question, how does DOS switch to using the alternate layout we provide?

**Comment by andrewbird** [comment] 2019-06-04 09:16
Oh yes, In my earlier experiments with my sdlttf-01 branch I had removed the xkb stuff in a similar way to your sdl_key branch, but I did find that it was possible to see the country remapped keys but as I don't have a physical fr or de keyboard I couldn't test whether this was the right thing to do for real keyboards. See this snippet of code I found on the web
```C
/* checks if a key is being remapped and prints what the remapping is */
if (keysym.scancode != SDL_GetScancodeFromKey(keysym.sym)) {
     v_printf("Physical %s key acting as %s key",
                 SDL_GetScancodeName(keysym.scancode),
                 SDL_GetKeyName(keysym.sym));
}
```

**Comment by stsp** [comment] 2019-06-04 09:20
Could you please figure out if
SDL_process_key_text() is ever
being called for you, and if so - if
the character is valid?

There is no "dos switch", we do the
translation on bios level.

**Comment by andrewbird** [comment] 2019-06-04 09:56
With this patch, and FR keymap active
```C
diff --git a/src/plugin/sdl/sdl.c b/src/plugin/sdl/sdl.c
index 4952764b1..72a0c32e6 100644
--- a/src/plugin/sdl/sdl.c
+++ b/src/plugin/sdl/sdl.c
@@ -843,9 +843,14 @@ static void SDL_handle_events(void)
 #endif
        rc = SDL_PeepEvents(&text_event, 1, SDL_GETEVENT, SDL_TEXTINPUT,
                SDL_TEXTINPUT);
-       if (rc == 1 && event.key.timestamp == text_event.text.timestamp)
-           SDL_process_key_text(event.key, text_event.text);
-       else
+       if (rc == 1 && event.key.timestamp == text_event.text.timestamp) {
+            SDL_Keysym keysym = event.key.keysym;
+            v_printf("SDL_process_key_text called\n");
+            v_printf("Physical %s key acting as %s key",
+                SDL_GetScancodeName(keysym.scancode),
+                SDL_GetKeyName(keysym.sym));
+            SDL_process_key_text(event.key, text_event.text);
+       } else
            SDL_process_key_press(event.key);
       }
       break;
```

Typing `qwerty` keys on physical keyboard with FR keymap active, shows `azerty` in normal terminal but `qwerty` in Dosemu.

~~~
SDL_process_key_text called
Physical Q key acting as A key

SDL_process_key_text called
Physical W key acting as Z key

SDL_process_key_text called
Physical E key acting as E key

SDL_process_key_text called
Physical R key acting as R key

SDL_process_key_text called
Physical T key acting as T key

SDL_process_key_text called
Physical Y key acting as Y key
~~~

**Comment by stsp** [comment] 2019-06-04 10:23
Please print text_event.text.text instead.

**Comment by andrewbird** [comment] 2019-06-04 10:41
~~~
SDL_process_key_text called                                                     
Physical Q key acting as A key                                                  
text_event.text.text = 'a'                                                      
INT10: tty put char: page 0, char 0x71 'q'                                      

SDL_process_key_text called                                                     
Physical W key acting as Z key                                                  
text_event.text.text = 'z'                                                      
INT10: tty put char: page 0, char 0x77 'w'                                      

SDL_process_key_text called                                                     
Physical E key acting as E key                                                  
text_event.text.text = 'e'                                                      
INT10: tty put char: page 0, char 0x65 'e'                                      

SDL_process_key_text called                                                     
Physical R key acting as R key                                                  
text_event.text.text = 'r'                                                      
INT10: tty put char: page 0, char 0x72 'r'                                      

SDL_process_key_text called                                                     
Physical T key acting as T key                                                  
text_event.text.text = 't'                                                      
INT10: tty put char: page 0, char 0x74 't'                                      

SDL_process_key_text called                                                     
Physical Y key acting as Y key                                                  
text_event.text.text = 'y'                                                      
INT10: tty put char: page 0, char 0x79 'y'                                      
~~~

`text_event.text.text` seems to have the correct info, but somewhere later the value reverts, as you can see in the INT10 printf following.

**Comment by stsp** [comment] 2019-06-04 10:52
Could you please check if
charset_to_unicode_string()
sets the `key` properly?

**Comment by andrewbird** [comment] 2019-06-04 11:10
~~~
SDL_process_key_text called                                                     
Physical Q key acting as A key                                                  
text_event.text.text = 'a'                                                      
before charset_to_unicode_string(), p='a', key=0000                             
after charset_to_unicode_string(), p='', key=0061                               
INT10: tty put char: page 0, char 0x71 'q'                                      
                 
SDL_process_key_text called                                                     
Physical W key acting as Z key                                                  
text_event.text.text = 'z'                                                      
before charset_to_unicode_string(), p='z', key=0000                             
after charset_to_unicode_string(), p='', key=007a                               
INT10: tty put char: page 0, char 0x77 'w'                                      

SDL_process_key_text called                                                     
Physical E key acting as E key                                                  
text_event.text.text = 'e'                                                      
before charset_to_unicode_string(), p='e', key=0000                             
after charset_to_unicode_string(), p='', key=0065                               
INT10: tty put char: page 0, char 0x65 'e'                                      
~~~

Looks okay to me.

**Comment by andrewbird** [comment] 2019-06-04 11:21
I turned on `k` debug
~~~
SDL_process_key_text called                                                     
Physical Q key acting as A key                                                  
text_event.text.text = 'a'                                                      
before charset_to_unicode_string(), p='a', key=0000                             
after charset_to_unicode_string(), p='', key=0061                               
move_key: keynum=0010                                                           
put_keynum_r: old_make:0 make:1 key:10                                          
translate_key: make=1, key=0010, input                                          
KBD: translate(old_shiftstate=0000, shiftstate=0000, key=0010)                  
KBD: translated key = 0071                                                      
KBD: writing to queue: scan=00000010                                            
KBD: resize queue 0->255 head=0 tail=0 level=0                                  
KBD: queuelevel=1                                                               
KBD: read queue: raw=10, queuelevel=0                                           
~~~

**Comment by andrewbird** [comment] 2019-06-04 11:32
This seems to work at least in the simple case
```C
-       SDL_Scancode scan = keysym.scancode;
+       //SDL_Scancode scan = keysym.scancode;
+       SDL_Scancode scan = SDL_GetScancodeFromName(p);
```

**Comment by stsp** [comment] 2019-06-04 11:42
But this should not be needed AFAICT,
because even the old code didn't.
Could you please compare the args
to move_keynum() with and w/o my
patch?

**Comment by stsp** [comment] 2019-06-04 13:23
Could you please summarize?
- The old xkb code didn't work properly?
- The new one doesn't either?
- There is no regression compared to the old one?

**Comment by andrewbird** [comment] 2019-06-04 14:00
- both the old xkb code and new sdl code only use the primary keymap, switching keymap involves reordering them in keyboard config tool.
- the new sdl code with the addition of `scan = SDL_GetScancodeFromName(p)` in `SDL_process_key_text()` will use the active keymap just like other desktop apps, one mouse click or keystroke to switch.
- both old xkb and new sdl code, autodetection of layout is done via the X_plugin at dosemu startup. Currently limited to two layouts (main + alternate) though I still don't understand how the alternate is ever used.

In essence the new code is no worse than old xkb derived code and has the benefit of less dependence on the X plugin, but someone with a native keyboard with funky keys/characters should try it.

**Comment by stsp** [comment] 2019-06-04 14:07
> SDL_process_key_text() will use the active keymap just like other desktop apps

Yes but I don't think this is the right thing to do.
Will investigate further.

> both old xkb and new sdl code, autodetection of layout is done via the X_plugin at dosemu startup.

This is simply because the X plugin is still loaded from
SDL. This detection should not be used by the new code.
You can as well comment it out and see if something breaks.

> but someone with a native keyboard with funky keys/characters should try it.

I can simulate the funky key remapping by just altering
the text.text field. So should be quite easy to reproduce.

**Comment by andrewbird** [comment] 2019-06-04 14:48
So using your latest sdl_key branch I installed display.exe and 858 codepage (850 + euro symbol), made DE layout primary and it looks beautiful except that I can't generate the euro symbol. Perhaps something in Dosemu mapping needs updating?
![codepage858](https://user-images.githubusercontent.com/220835/58888443-4da50480-86df-11e9-9ec6-13fb44807773.png)

In standard X window for my DE layout the key to press for Euro symbol is Alt-Gr + 'E', in DOS window nothing is printed.

**Comment by stsp** [comment] 2019-06-04 15:11
Can you get the Euro sign with keyb.com first?
Anyway, this is a different problem.
What do you mean by "looks beautiful", if initially
you were saying it does not respect azerty?

**Comment by andrewbird** [comment] 2019-06-04 15:30
> made DE layout primary and it looks beautiful except that I can't generate the euro symbol.

'azerty' is available(on FR keyboard) only by adjusting desktop settings to make it the primary map, I'd really like it to be available easily by the normal 'active' method that other apps use, but it's no worse than previous xkb code.

> looks beautiful

Because I can generate umlaut (ö)

I didn't think I needed to use keyb.exe on dosemu, that was my impression after reading https://github.com/stsp/dosemu2/issues/43#issuecomment-120750209 again. I'll try again.

How are you feeling about merging sdl_key branch?

**Comment by andrewbird** [comment] 2019-06-04 15:39
yes Euro symbol works with keyb.exe

~~~
C:\>keyb de
FreeDOS KEYB 2.01  - (c) Aitor Santamaría Merino - GNU GPL 2.0
Keyboard layout    : C:\DOS\KEYBOARD.SYS:DE [858]  (3)
C:\>€€€€
~~~

**Comment by stsp** [comment] 2019-06-04 15:43
> I didn't think I needed to use keyb.exe on dosemu

You don't have to, but you _can_.
And for the testing of Euro sign this will do.
If you can't get it even with keyb.com, then
its not a dosemu fault obviously.
EDIT: ok, thanks for info, so it _is_ a dosemu fault.
Lets get it another ticket then.

> How are you feeling about merging sdl_key branch?

OK, if there are no regressions, then lets merge.
Current keyboard code appears not to work the way I
expected. Namely, `put_keynum()` loses the `sym`
forever after finding its map. It shouldn't.
So we will either need to do what you suggest, or use
other work-arounds like `put_modified_symbol()`.
I'll evaluate how difficult is to propagate the `sym`
down the stack fully.

**Comment by stsp** [comment] 2019-06-04 15:45
I merged the new code.
Please don't hesitate to open the ticket about
azerty problem.

**Comment by andrewbird** [comment] 2019-06-04 15:52
Cool, I'll rebase my sdl_ttf on it then, thanks.

**Comment by andrewbird** [comment] 2019-06-04 20:56
So sdlttf is coming along okay. Do you know how/where the focussed block cursor for insert mode is implemented? I have the overwrite under bar done, but can't see in either original SDL or X plugin how that gets changed upon pressing the insert key.

**Comment by stsp** [comment] 2019-06-04 22:24
There is no "insert mode" or "insert mode cursor".
If some particular app implements such thing, it
would adjust the vga crtc registers.
See `draw_cursor(void)`:
```
    Text->Draw_cursor(Text->opaque, x, y, XATTR(cursor),
                      CURSOR_START(vga.crtc.cursor_shape),
                      CURSOR_END(vga.crtc.cursor_shape), have_focus);
```

`vga.crtc.cursor_shape` is a culprit here.
If you see the empty square, then this is a focus-out
cursor, not insert cursor.

**Comment by andrewbird** [comment] 2019-06-04 22:44
I'll look at cursor shape, though in x and old SDL code I do see three types of cursor: rectangle, underline and the solid block one I'm missing.

**Comment by andrewbird** [comment] 2019-06-04 23:19
Thanks, I looked harder at the old code. It seems that the `vga.char_height` must vary according to whether the DOS prompt is in insert or overwrite mode which generates the two different cursor styles I see for in-focus.

**Comment by stsp** [comment] 2019-06-05 00:29
Where do you see that?

**Comment by andrewbird** [comment] 2019-06-05 09:18
It's the cstart/cend vars in the focussed mode that give me solid block or underbar cursors. 
```C
static void SDL_draw_text_cursor(void *opaque, int x, int y, Bit8u attr,        
                               int start, int end, Boolean focus)               
{                                                                               
  SDL_Rect rect;                                                                
                                                                                
  if (vga.mode_class == GRAPH)                                                  
    return;                                                                     
                                                                                
  if (!focus) {                                                                 
    rect.x = font_width * x;                                                    
    rect.y = font_height_nl * y;                                                
    rect.w = font_width;                                                        
    rect.h = font_height - 1;                                                   
                                                                                
    pthread_mutex_lock(&rend_mtx);                                              
    SDL_SetRenderDrawColor(renderer,                                            
                           text_colors[ATTR_FG(attr)].r,                        
                           text_colors[ATTR_FG(attr)].g,                        
                           text_colors[ATTR_FG(attr)].b,                        
                           text_colors[ATTR_FG(attr)].a);                       
    SDL_RenderDrawRect(renderer, &rect);                                        
    pthread_mutex_unlock(&rend_mtx);                                            
                                                                                
  } else {                                                                      
    int cstart, cend;                                                           
                                                                                
    cstart = ((start + 1) * font_height_nl) / vga.char_height - 1;              
    if (cstart == -1)                                                           
      cstart = 0;                                                               
    cend = ((end + 1) * font_height_nl) / vga.char_height - 1;                  
    if (cend == -1)                                                             
      cend = 0;                                                                 
                                                                                
    rect.x = font_width * x;                                                    
    rect.y = font_height_nl * y + cstart;                                       
    rect.w = font_width;                                                        
    rect.h = cend - cstart + 1;                                                 
                                                                                
    pthread_mutex_lock(&rend_mtx);                                              
    SDL_SetRenderDrawColor(renderer,                                            
                           text_colors[ATTR_FG(attr)].r,                        
                           text_colors[ATTR_FG(attr)].g,                        
                           text_colors[ATTR_FG(attr)].b,                        
                           text_colors[ATTR_FG(attr)].a);                       
    SDL_RenderFillRect(renderer, &rect);                                        
    pthread_mutex_unlock(&rend_mtx);                                            
  }                                                                             
                                                                                
  pthread_mutex_lock(&rects_mtx);                                               
  sdl_rects_num++;                                                              
  pthread_mutex_unlock(&rects_mtx);                                             
}                                                                               
```

A video [new_sdl_text_cursor.zip](https://github.com/stsp/dosemu2/files/3256406/new_sdl_text_cursor.zip) showing (focussed insert)`underbar`, (focussed overwrite)`block` and (unfocussed)`rectangle`

**Comment by stsp** [comment] 2019-06-05 10:44
This is because comcom32 does this:
```
  flag = keyb_get_shift_states();
  if (flag&KEYB_FLAG_INSERT)
    _setcursortype(_NORMALCURSOR);
  else
    _setcursortype(_SOLIDCURSOR);
```

This has nothing to do with sdl, x or "three types of cursor".
There are only 2: focus-out and user-defined.

**Comment by andrewbird** [comment] 2019-06-05 11:04
Yes I wasn't respecting the user-definition.

**Comment by stsp** [comment] 2019-06-05 11:16
The flags above are obviously inverted btw.
I changed that now.

**Comment by andrewbird** [comment] 2019-06-05 12:11
I didn't notice as I'm using freecom.

**Comment by stsp** [comment] 2019-06-05 12:37
> I didn't notice as I'm using freecom.

No, this was noticeable from the comcom32's code snippet above.
Its obviously wrong. `INSERT` sets `_NORMALCURSOR` and
`!INSERT` sets `_SOLIDCURSOR`.

**Comment by stsp** [comment] 2019-06-05 17:31
Hi Andrew, could you please test the new i18n kbd patch?

**Comment by andrewbird** [comment] 2019-06-05 23:12
It seems much better than before. Were you expecting that you had fixed euro symbol input and switching on active keymaps?

**Comment by stsp** [comment] 2019-06-06 08:34
Thanks.
No, I didn't think about a euro symbol
yet. But if it got fixed, then the problem
is in the kbd layout table. Either you
load the wrong one or it doesnt define
that symbol for the proper key.
But switching the keymaps should
work correctly now, and I intended to
fix the azerty problem. Was it fixed?

In fact, I wonder why no one have yet
tried such a small patch. It bypasses
the layout tables completely, so the
new kbd code in sdl, which is itself just
a couple of lines, uses only 1/3 of the
generic kbd code. Much simpler than
what comes out from an X backend.

**Comment by andrewbird** [comment] 2019-06-06 08:46
Yes azerty problem is fixed, thanks.

**Comment by andrewbird** [comment] 2019-06-06 10:12
I checked the keymaps and none of the latin1 contain the 0xd5 used in the 858 codepage. The DE and UK keyboards generate Euro by using the AltGr key, that's AltGr-E and AltGr-4 respectively. I don't see how the keymap files could encode those, as there is only a plain Alt map which doesn't achieve the same thing.

Anyway, I love what you've just done for SDL mode, so I'm not going to worry about X and slang.

**Comment by stsp** [comment] 2019-06-06 12:38
> I checked the keymaps and none of the latin1 contain the 0xd5 used in the 858 codepage.

Unicode representation is used in the maps.
So try 0x20AC instead.

> how the keymap files could encode those, as there is only a plain Alt map which
> doesn't achieve the same thing.

It appears that it actually does:
```
        /* altgr keys */
        if (key_table->alt_map) {
                init_translate_rule(rules->trans_rules.rule_structs.altgr.rule_map,
                                     key_table->sizemap, key_table->alt_map, 0);
        }
```
So as confusing as it is, alt map in a keytable
is actually an altgr map in the translation code.
So please try to use it.

> Anyway, I love what you've just done for SDL mode, so I'm not going to worry about X and slang.

Unfortunately we still need to support slang.
And I don't think the layout-bypass trick I did
for sdl, is ever possible with slang.
So it would be very nice if you look into adjusting
the keytables.

**Comment by andrewbird** [comment] 2019-06-06 15:39
Maybe I'm looking at the wrong thing for keymap, but I etc/keymaps/uk doesn't seem to have Unicode

```C
#keytable uk                                                                    
keytable keyb-user {                                                            
  0=                                                                            
     0,27,"1234567890-=",127,9,                                                 
     "qwertyuiop[]",13,0,"as",                                                  
     "dfghjkl;",39,96,0,"#zxcv",                                                
     "bnm,./",0,"*",0," ",0,0,0,0,0,0,                                          
     0,0,0,0,0,0,0,0,0,0,"-",0,0,0,"+",0,                                       
     0,0,0,0,0,0,92,0,0,0,0,0,0,0,0,0,                                          
     0                                                                          
  shift 0=                                                                      
     0,27,"!",34,156,"$%^&*()_+",127,9,                                         
     "QWERTYUIOP{}",13,0,"AS",                                                  
     "DFGHJKL:@~0~ZXCV",                                                        
     "BNM<>?",0,"*",0," ",0,0,0,0,0,0,                                          
     0,0,0,0,0,0,0,0,0,0,"-",0,0,0,"+",0,                                       
     0,0,0,0,0,0,"|",0,0,0,0,0,0,0,0,0,                                         
     0                                                                          
  alt 0=                                                                        
     0,0,0,"@",0,"$",0,0,"{[]}",92,0,0,0,                                       
     0,0,0,0,0,0,0,0,0,0,0,"~",13,0,0,0,                                        
     0,0,0,0,0,0,0,0,dacute,dgrave,0,dtilde,0,0,0,0,                            
     0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,                                           
     0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,                                           
     0,0,0,0,0,0,"|",0,0,0,0,0,0,0,0,0,                                         
     0                                                                          
  numpad 0=                                                                     
     "789-456+1230."                                                            
}                                                                               
```

But as you say the alt map seems to be alt-gr as if I apply this patch, then Euro key works fine (in -X and -t)
```C
diff --git a/etc/keymap/uk b/etc/keymap/uk
index 972d8edb9..03e30464c 100644
--- a/etc/keymap/uk
+++ b/etc/keymap/uk
@@ -17,7 +17,7 @@ keytable keyb-user {
      0,0,0,0,0,0,"|",0,0,0,0,0,0,0,0,0,
      0
   alt 0=
-     0,0,0,"@",0,"$",0,0,"{[]}",92,0,0,0,
+     0,0,0,"@",0,0xd5,0,0,"{[]}",92,0,0,0,
      0,0,0,0,0,0,0,0,0,0,0,"~",13,0,0,0,
      0,0,0,0,0,0,0,0,dacute,dgrave,0,dtilde,0,0,0,0,
      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
```

**Comment by stsp** [comment] 2019-06-06 16:33
Most keymaps are hardcoded in keymaps.c and do
use unicode. I am surprised the textual keymaps are
that different, but oh well...
Please see if there are some maps to correct also in
keymaps.c, and open a PR.

**Comment by andrewbird** [comment] 2019-06-06 17:18
None of the files in etc/keymaps or the definitions in src/base/kbd_unicode/keymaps.c have the euro key. I wonder why there's duplication in keymap definition?

**Comment by stsp** [comment] 2019-06-06 18:26
Some study of changelog revealed that the
/etc/* keymaps were dumped from the ones
in keymap.c when the dumper was written.
This was done so that people can adjust them
easily. For example, there were something like
5 different russian keyboard layouts in Russia
for the last 40 years. At least the ones I am aware
of - there could be much more. So having the maps
alterable was a good idea, but they were not removed
from keymaps.c after dumping.
Then keymaps.c was converted to unicode, but it
doesn't look like the tables were re-dumped.

Just yesterday I'd say lets clean up the mess, re-dump
them in unicode form and all that. But now - what's the
use? We don't need them for SDL, and only for slang the
hardcoded tables should be enough.
So... delete the non-unicode external tables and update
the unicode ones? What do you think?

**Comment by andrewbird** [comment] 2019-06-06 18:48
I wonder if anyone uses custom external keymaps, I don't and for me your suggestion is sound. I guess you'll need to open another issue for that or else it'll get forgotten.

So moving back to the SDL ttf stuff, I need to implement speaker in SDL since I removed X plugin usage. Can I inject beep sound into sound system from there? I suppose it needs to be mixed if there's something already playing.

**Comment by andrewbird** [comment] 2019-06-06 18:56
This looks like a source of inspiration https://github.com/chocolate-doom/chocolate-doom/blob/master/pcsound/pcsound_sdl.c

**Comment by stsp** [comment] 2019-06-06 19:29
This one uses SDL_mixer.
We have our own mixer API.
So the speaker code should not be
sdl-specific. It should instead be generic.
The basic procedure is to call
pcm_allocate_stream() at init, then call
pcm_write_interleaved() sequentially, then
when there is no more sound data on the
way, you call pcm_flush().

Please find these 3 calls in mid_o_flus.c
for the example code. Its very simple.

**Comment by stsp** [comment] 2019-06-06 19:50
pc-speaker can as well be done later.

**Comment by stsp** [comment] 2019-06-06 19:52
> I wonder if anyone uses custom external keymaps

Very probably, but conjunct these people with the ones
that use slang backend...

**Comment by stsp** [comment] 2019-06-06 20:09
> None of the files in etc/keymaps or the definitions in src/base/kbd_unicode/keymaps.c have the euro key.

Euro only appeared in 2002.
No wonder dosemu's tables do not have it.
In 2002 dosemu1's development was already
fading out. And when the Euro sign became popular
on the keyboards, I suppose dosemu1 was already
at a full-stop.

**Comment by andrewbird** [comment] 2019-06-06 22:34
> Euro only appeared in 2002.
No wonder dosemu's tables do not have it.

They added some of the Euro support just not the keymaps it seems.

```
commit 8eed6411827551083a01697c776d3e5ef277ba7b
Author: Bart Oldeman <bartoldeman@users.sourceforge.net>
Date:   Mon Apr 1 17:56:41 2002 +0100

    2002/01/23 ver 1.1.2.8 unofficial pre-release

            From Eric
            - Add cp858 support cp850 + EURO
```

**Comment by andrewbird** [comment] 2019-06-06 23:12
##### TODO
- [x] cursor
- [x] I18N keyboard (stas)
- [x] I18N display
- [x] colours
- [ ] resize
  - [x] normal window resize
  - [ ] fullscreen
  - [ ] maximised
- [ ] implement speaker
- [x] line draw (untested)
- [ ] odd initial window position
- [ ] font path
- [ ] review text_lock() / text_unlock() functions

**Comment by stsp** [comment] 2019-06-06 23:45
Yes, unicode standard was quickly
updated, so dosemu could update
the tables in 2002. But if the keyboards
with that sign became popular few
years later, then they wold be left out
exactly for the reason that dosemu1
was at a full-stop.

Looks like quite a lot is in todo.
But resizing and font path look the
only things that really matter short-term.
IIRC text_lock/text_unlock are only
for optimization. They provide the bulk
update on unlock, rather than per-char.
They were not for concurrency problems,
if my memory is correct.

**Comment by andrewbird** [comment] 2019-06-07 14:53
I have fontconfig working now to find the ttf font. What are your thoughts on how to package (or not) the ttf fonts we use as default? I'm using this font https://int10h.org/blog/2018/05/flexi-ibm-vga-scalable-truetype-font/ which has this to say about licence
~~~
  These fonts are released under the Creative Commons Attribution-ShareAlike    
  4.0 International license: http://creativecommons.org/licenses/by-sa/4.0/     
~~~

**Comment by skitt** [comment] 2019-06-07 15:16
> > None of the files in etc/keymaps or the definitions in src/base/kbd_unicode/keymaps.c have the euro key.
> 
> Euro only appeared in 2002.

PC DOS supported it in 1998, and the € key was common on French PC keyboards by then. (Just a historical tidbit.)

**Comment by stsp** [comment] 2019-06-07 16:03
> What are your thoughts on how to package (or not) the ttf fonts we use as default?

If they are not already packaged by distros, we
can provide them. cc-by-sa is an FSF approved license AFAIK.

**Comment by stsp** [comment] 2019-06-30 21:22
> TODO

One important TODO point missing: we do not
have the scaling filters in SDL mode (unless
you set `$_SDL_hwrend=(on)` in which case
we do).

**Closed** 2021-02-14 17:58 UTC
Labels: enhancement, todo
