### ISSUE TITLE
Moving mouse in Borland Pascal IDE crashes DOSEmu

### ISSUE THREAD

**Issue by jharrison03** [dosemu2/dosemu2#1394] opened 2021-01-28 17:07 UTC
**Describe the bug**
Start the Borland Pascal 7.01 IDE and move the mouse cursor.  DOSEmu will crash with the following printed to the console --

`ERROR: KVM_EXIT_FAIL_ENTRY: hardware_entry_failure_reason = 0x80000021
`

(DOSEmu doesn't crash in the same fashion with Borland C++ 3.1).

**To Reproduce**
See above.

**Attach program/game binaries or provide an URL**
[bp701.zip](https://github.com/dosemu2/dosemu2/files/5888937/bp701.zip)

**Attach the log**
[boot.log.zip](https://github.com/dosemu2/dosemu2/files/5888834/boot.log.zip) (-D+m)

**A regression?**
Yes, it worked the last time I used it, probably two weeks ago.

**Additional info**
None at this time.

**Comment by andrewbird** [comment] 2021-01-28 17:10
> ERROR: KVM_EXIT_FAIL_ENTRY: hardware_entry_failure_reason = 0x80000021

Does this happen every time, or is there some randomness?

**Comment by jharrison03** [comment] 2021-01-28 17:16
> > ERROR: KVM_EXIT_FAIL_ENTRY: hardware_entry_failure_reason = 0x80000021
> 
> Does this happen every time, or is there some randomness?

No, the BP IDE crashes immediately and consistently, whenever the mouse is first moved.

The BP IDE doesn't crash, as long as you keep your hand off the mouse.

**Comment by stsp** [comment] 2021-01-28 21:09
I tried on bp-7.0 that I have here and
it works fine.
Could you please bisect this?

**Comment by stsp** [comment] 2021-01-28 21:21
Your pascal works for me as well, mouse works.

**Comment by stsp** [comment] 2021-02-06 20:39
Is this still a problem?

**Comment by stsp** [comment] 2021-02-20 13:35
No reply and can't reproduce.

**Comment by stsp** [comment] 2021-04-24 20:06
Is this now fixed?

**Comment by jharrison03** [comment] 2021-04-27 15:32
No, it still crashes - but If set $_cpu_vm_dpmi = "native", then it doesn't.  I haven't followed up on this, because I'm probably the only person running this on a 32-bit kernel and I don't want to be a pain in the ass "edge case" person.  But here's the logs --

$_cpu_vm_dpmi = "native" 

[boot.log-dpmi_native.zip](https://github.com/dosemu2/dosemu2/files/6385748/boot.log-dpmi_native.zip)

$_cpu_vm_dpmi = "auto"

[boot.log-auto.zip](https://github.com/dosemu2/dosemu2/files/6385767/boot.log-auto.zip)

**Comment by stsp** [comment] 2021-04-27 20:42
Could you please try the kvm_syn
branch?

**Comment by jharrison03** [comment] 2021-05-10 03:34
> Could you please try the kvm_syn
> branch?

I will, as soon as I install a newer distro.

**Comment by stsp** [comment] 2021-08-20 17:17
I think this is fixed in be7dea77fe.
Could you please re-check?

**Closed** 2021-12-12 01:02 UTC
Labels: kvm
