### ISSUE TITLE
Fedora Copr repository has semi-broken dependencies.

### ISSUE THREAD

**Issue by Nobody-Special** [dosemu2/dosemu2#2177] opened 2024-03-26 09:22 UTC
Hi All; long time, no see :)
I have come again to report a bug regarding Fedora repo.

**Describe the bug**
While installing dosemu2 on Fedora 39 from Copr stsp/dosemu2 the installation is half broken.

**To Reproduce**
Steps to reproduce the behaviour:
```sh
#> sudo dnf copr enable dosemu2
#> sudo dnf install dosemu2
```

**Attach program/game binaries or provide an URL**
Not Applicable.

**Attach the log**
<details>
<summary><del>~/.dosemu/boot.log</del></summary>

```
FDPP kernel "- GIT " (compiled Mar 18 2024)
fdpp: plugin loaded: 1
booting with comcom64
CONF: config variable parser_version_3 set
CONF: config variable c_system set
CONF: Parsing built-in dosemu.conf file.
CONF: config variable version_3_style_used set
CONF: Parsing /etc/dosemu/dosemu.conf file.
CONF: Parsing built-in global.conf file.
CONF: mapping driver = 'auto'
debug flags: -a+cw
CONF: timer freq=18, update=54925
CONF: CPU set to 586
CONF: CPUEMU set to jit
CONF: CPU VM set to -1
CONF: CPU VM set to -1 for DPMI
CONF: 8192k bytes EMS memory
CONF: EMS-frame = 0xe000
CONF: dos_up: on
CONF: DPMI-Server on (0x20000)
CONF: DPMI base addr = 0x20000000
CONF: PM DOS API Translator on
CONF: No DJGPP NULL deref checks: on
CONF: 8192k bytes int15 ext memory
CONF: 16384k bytes XMS memory
Warning: CONF: dosemu not running on console
CONF: time mode = 'bios'
SER: directory /var/lock namestub LCK.. binary No
MOUSE: /dev/input/mice, type 7 using internaldriver: yes, emulate3buttons: no baudrate: 0
Warning: CONF: **** Warning: floppy /dev/fd0 not accessible, disabled
CONF: fastfloppy = 1
default_drives 0
Setting up drive C, /home/kami/.dosemu/drive_c
Added drive 0 (80): /home/kami/.dosemu/drive_c
default_drives 1
Added drive 1 (81): /usr/share/dosemu/dosemu2-cmds-0.3
Setting up default drives from E
Added drive 2 (82): /usr/share/comcom64
CONF: IPX support off
CONF(LPT0) f: (null)   c: lpr -l  t: 20  port: 0
CONF(LPT1) f: (null)   c: lpr -P PDF  t: 20  port: 0
CONF: not allowing speaker port access
CONF: Packet Driver enabled.
CONF: NE2000 enabled.
CONF: config variable c_system unset
Command line: /usr/bin/dosemu.bin -o /home/kami/.dosemu/boot.log -td -ks -V
Warning: Your CPU doesn't support UMIP
Warning: Linux kernel 6.7.9; CPU speed is 3923833000 Hz
Warning: CPU-EMU speed is 3924 MHz
CONF: V86 cpu vm set to -1
CONF: DPMI cpu vm set to -1
CONF: not running on console
CONF: mostly running as USER: uid=1000 (cached 1000) gid=1000 (cached 1000)
CONF: priv operations unavailable
Warning: dosemu2-2.0pre9 is coming up on Linux version 6.7.9-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Mar  6 19:35:04 UTC 2024 x86_64
Warning: Compiled with gcc version 13.2.1Warning:  64bit
Warning: CFLAGS: -fplan9-extensions -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -Wno-unused-result -Wcast-qual -Wwrite-strings -Wstrict-aliasing=2 -Wundef -Wno-address-of-packed-member -ggdb3 -fpie -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer
CONF: reserving 640Kb at 0x00000 for 'd' (Base DOS memory (first 640K))
CONF: reserving 16Kb at 0xFA000 for 'r' (Dosemu reserved area)
CONF: reserving 8Kb at 0xFE000 for 'b' (BIOS)
Warning: Using V86 mode inside KVM
VID: Video set to Video_none
CONF: reserving 32Kb at 0xB8000 for 'v' (Video memory)
Registering HWRAM, type=L base=0 size=0x110000
Conventional memory mapped from 0x7ff5a8400000 to 0x7ff57da00000
CONF: reserving 16384Kb at 0x900000 for 'x' ((null))
CONF: reserving 8128Kb at 0x110000 for 'X' (EXT MEM)
Registering HWRAM, type=X base=0x110000 size=0x1ef0000
Registering HWRAM, type=U base=0x28710000 size=0x1ef0000
CONF: reserving 64Kb at 0x100000 for 'H' (HMA)
loading fonts for cp852
VID: initializing video none
Warning: SERIAL $Id$
DPMI: mem init, mpool is 140468224 bytes at 0x7ff59da00000
Warning: Using DPMI inside KVM
CONF: detected layout is "us"
CONF: detected alternate layout: (null)
TIME: using 9154 usec for updating ALRM timer
CONF: freeing region for 'E' (EMS page frame)
booting with comcom32
config.boot_dos set to 400000
config.int_hooks set to 0
config.force_revect set to 0
CONF: reserving 96Kb at 0xA0000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
CONF: reserving 128Kb at 0xC0000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
CONF: reserving 40Kb at 0xF0000 for 'U' (Upper Memory Block (UMB, XMS 3.0))
CONF: reserving 16Kb at 0xE0000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xE4000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xE8000 for 'E' (EMS page frame)
CONF: reserving 16Kb at 0xEC000 for 'E' (EMS page frame)
cannot dlopen /dev/shm/dosemu_COMMAND.COM: /dev/shm/dosemu_COMMAND.COM: odwzorowanie segmentu z obiektu dzielonego nie powiodło się
leavedos(fdpp_exit:96|0) called - shutting down
leavedos thread started
leavedos thread ended
coopthreads stopped
```
</details>

**A regression?**
<del>Yes.</del>
Installs and works correctly.
Only DNF is complaining about mismatched dependencies. 

**Additional info**
DNF is complaining about:
 1. missmatched versions of fdpp (installed: libfdpp.so.35.10; expected: libfdpp.so.34.10)
 2. missing comcom32 (comcom64 installs just fine)

<del>I'm guessing that: "cannot dlopen /dev/shm/dosemu_COMMAND.COM: /dev/shm/dosemu_COMMAND.COM" is related to missing comcom32.</del>. I have forgot to mention, that I've been running `dosemu2` inside a sandbox (toolbox). In short: "Don't do that".

dosemu2 launches itself without a problem (either in Slang, X or SDL mode).

**Comment by stsp** [comment] 2024-03-26 09:42
I don't understand what's going on.
dnf installs `dosemu2-0.0.git.651.7965f088-1.fc40.x86_64`
and says that `dosemu2-0.0.git.738.0dd69f12-1.fc40.x86_64`
has broken deps.
But on COPR the latest build is
`dosemu2 0.0.git.645.a235ad7e`.

There is something wrong with
the build number assignment, it
is not incremental.
I'll ask for help at fedora.

In a mean time, the dlopen problem
is likely because you have `noexec`
mount of `/dev/shm`. comcom64
currently doesn't support this, and I
am not sure if it ever will (the problem
can be solved on a linux kernel side only).

**Comment by stsp** [comment] 2024-03-26 10:01
Actually, @praiskup can you give us
some help with the build numbering?
https://copr.fedorainfracloud.org/coprs/stsp/dosemu2/build/7205187/
Submitted:
    2024-03-23 11:36 UTC (2 days ago)
This is the latest dosemu2 build, and
it is called `0.0.git.645.a235ad7e-1`,
and the previous one is:
https://copr.fedorainfracloud.org/coprs/stsp/dosemu2/build/7205182/
Submitted:
    2024-03-23 11:26 UTC (2 days ago) 
(i.e. 10 minutes before the last one)
It is called:
`0.0.git.647.559e68ea-1`

647 is greater than 645...
Well, this is supposed to be a
commit count number, emitted
by `git_version` rpkg macro.
I'd expect it to match `git describe`,
but:
```
$ git describe --tags
2.0pre9-dev-1795-ga235ad7e3
```

1795 is not even remotely close
to what `git_version` emits.
What's going on here, any help?

**Comment by Nobody-Special** [comment] 2024-03-26 10:28
> In a mean time, the dlopen problem
> is likely because you have `noexec`
> mount of `/dev/shm`. comcom64
> currently doesn't support this, and I
> am not sure if it ever will (the problem
> can be solved on a linux kernel side only).

Gosh. I'm glad that you have mentioned it.
I can confirm that it is indeed related to
`noexec` mount of `/dev/shm`.

Thankfully I'm a complete idiot as I forgot to mention
that I've been running `dosemu2` inside a sandbox (toolbox).

Running on bare metal works and the COMMAND shell launches.

P.S. I'll update the bug report to reflect this.

**Comment by Nobody-Special** [comment] 2024-03-26 10:43
By the way... Maybe `README.md` should mention
that you need `/dev/shm` mounted without `noexec`?

Maybe FAQ section in `README.md` is due?

**Comment by stsp** [comment] 2024-03-26 10:58
Maybe, but lets keep this ticket
for the `git_dir_version` problem,
or @praiskup will not be able to
provide any help.

**Comment by stsp** [comment] 2024-03-26 13:38
> 647 is greater than 645...

Now it generated 643:
https://copr.fedorainfracloud.org/coprs/stsp/dosemu2/build/7216460/
It almost looks like its counting
backwards, with the step of 2!
How can that be?

**Comment by stsp** [comment] 2024-03-26 14:07
`rpkg local` generates this:
`Version: 0.0.git.11467.e4600330`
... which is correct.
So the problem is specific to COPR.
There is something wrong with rpkg
macros there.
@praiskup what kind of rpkg macros
does the copr have? Maybe its outdated?

**Comment by stsp** [comment] 2024-03-26 14:12
On other packages the numbers
mismatch too. fdpp on copr:
`0.0.git.1583.5e68fbeb-1`
and locally:
`0.0.git.2392.5e68fbeb`

**Comment by stsp** [comment] 2024-03-28 12:05
I filled up the ticket on copr:
https://github.com/fedora-copr/copr/issues/3196
Maybe there we can get some help.

**Comment by stsp** [comment] 2024-04-06 15:41
I think this is now fixed.
I switched the build to tito, seems
to work, but needs to watch and see.

**Closed as completed by stsp** 2024-04-06 15:41 UTC

**Comment by stsp** [comment] 2024-04-09 09:20
The aforementioned copr ticket got
some activity and discussion. Problem
was tracked to shallow clone.
Whoever is interested, can join the
discussion there.
