### ISSUE TITLE
dosemu2 fails to start after update

### ISSUE THREAD

**Issue by mcericdos** [dosemu2/dosemu2#1471] opened 2021-05-04 21:45 UTC
**Describe the bug**
After updating it, dosemu2 fails to start:

$ dosemu -X -C
dosemu.bin:
/build/dosemu2-9caBSp/dosemu2-2.0~pre8-6321/build/../src/arch/linux/async/signal.c:250:
registersig: Assertion `fun && !sighandlers[sig]' failed.

**To Reproduce**
dosemu -X -C

**Attach program/game binaries or provide an URL**
The binaries are from dosemu2 itself. Versions:

dosemu2-legacy/bionic,now 2.0#pre8-6321-f6be50a35+202105031133#ubuntu18.04.1 i386
comcom32/bionic,now 0.1#alpha2-147-c07e085+202105020117#ubuntu18.04.1 i386
fdpp/bionic,now 1.3-1152-488c1ae+202105030117#ubuntu18.04.1 i386

I have replaced the tildes by # to avoid messing up the bug report layout.

**Attach the log**
[dosemu2-bootlog.txt](https://github.com/dosemu2/dosemu2/files/6424103/dosemu2-bootlog.txt)

**A regression?**
Yes. The problem only appeared after I had updated dosemu2 to make fdpp and dosemu2 versions match again.

Before that, dosemu2 worked IF renaming /usr/lib/libfdpp.so to work around the fatal version mismatch error. When it cannot find the file at all, it only shows a warning, but proceeds to load. I think it should do the same on a version mismatch, too, by the way.

Note that because I am using a classic FreeDOS kernel.sys on my lredir C: drive, I should not need libfdpp.so to boot dosemu2 at all.

**Additional info**
This is the i386 version, which annoys the dosemu2 developers by existing at all, but Ubuntu 18.04 still has two years of LTS support and I prefer i386 when possible.

**Comment by stsp** [comment] 2021-05-04 22:34
Can't reproduce but I think its now fixed.

**Closed** 2021-05-04 22:34 UTC

**Comment by andy5995** [comment] 2021-05-31 20:30
I have this problem when building on Ubuntu Focal (in a docker container).

As root, in the container, I've used the ci scripts to get the prerequisites and do the build and install. I switched to an unprivileged user and ran `dosemu`

After building and installing as root, then switching to an unprivileged user:

```
ERROR: libfdpp.so: cannot open shared object file: No such file or directory
ERROR: can't load fdpp
ERROR: KVM: error opening /dev/kvm: No such file or directory
ERROR: userspace pings are disabled.
	To enable them, do as root:
	echo 0 65535 > /proc/sys/net/ipv4/ping_group_range
ERROR: term: stderr still on tty, closing
```

After adding the line `/usr/local/lib/dosemu` to /etc/ld.so.conf.d/libc.conf and then running `ldconfig`, and creating a symlink from libplugin_fdpp.so to libfdpp.so in /usr/local/lib/dosemu:

```
$ dosemu
/usr/local/bin/dosemu: symbol lookup error: /usr/local/lib/dosemu/libplugin_fdpp.so: undefined symbol: FdppInit
```

```
$ ldd dosemu.bin 
	linux-vdso.so.1 (0x00007ffc1dee3000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4dabf6f000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4dabf69000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4dabe1a000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f4dabe00000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f4dabdf5000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4dabc03000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4dac891000)
```

```
## --------- ##
## Platform. ##
## --------- ##

hostname = e1620c26eb2d
uname -m = x86_64
uname -r = 4.19.0-16-amd64
uname -s = Linux
uname -v = #1 SMP Debian 4.19.181-1 (2021-03-19)

/usr/bin/uname -p = x86_64
/bin/uname -X     = unknown

/bin/arch              = x86_64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /usr/sbin
PATH: /usr/bin
PATH: /sbin
PATH: /bin


## ----------- ##
## Core tests. ##
## ----------- ##

configure:2303: checking whether make supports nested variables
configure:2320: result: yes
configure:2351: checking whether to enable maintainer-specific portions of Makefiles
configure:2360: result: no
configure:2428: checking for gcc
configure:2444: found /usr/bin/gcc
configure:2455: result: gcc
configure:2684: checking for C compiler version
configure:2693: gcc --version >&5
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
```

**Comment by andy5995** [comment] 2021-05-31 20:58
That docker image is now public, btw, available at https://hub.docker.com/r/andy5995/dosemu2-dev

**Comment by stsp** [comment] 2021-05-31 21:53
We have the pre-built packages for
ubuntu focal.
Anyway, how have you built dosemu2?
Please open another ticket and show
the configure output.

**Comment by andy5995** [comment] 2021-05-31 22:30
> We have the pre-built packages for
> ubuntu focal.
> Anyway, how have you built dosemu2?
> Please open another ticket and show
> the configure output.

New ticket at https://github.com/dosemu2/dosemu2/issues/1485

**Comment by andy5995** [comment] 2021-05-31 22:44
> > We have the pre-built packages for
> > ubuntu focal.

I wanted to try building it to get a better understanding of it, because I might work on https://github.com/dosemu2/dosemu2/discussions/1482
