### ISSUE TITLE
Games which use MPU-401 IRQ don't produce music

### ISSUE THREAD

**Issue by jharrison03** [dosemu2/dosemu2#1772] opened 2022-08-21 06:09 UTC
**Describe the bug**
Games which use MPU-401 IRQ don't produce music.  A list of games with this requirement can be found here:  https://github.com/bjt42/softmpu/wiki/Compatible-Intelligent-Mode-Games

**To Reproduce**
Start any of the games listed at the softmpu link which require a MPU-401 interrupt and observe there is no music.

**Attach program/game binaries or provide an URL**
Two samples from the softmpu list --

David Wolf: 
[wolf.zip](https://github.com/dosemu2/dosemu2/files/9388539/wolf.zip)
Spellcasting 101
[sc101.zip](https://github.com/dosemu2/dosemu2/files/9388540/sc101.zip)

**Attach the log**
[boot.zip](https://github.com/dosemu2/dosemu2/files/9388549/boot.zip)

**A regression?**
It worked previously and I think this is related to 8190f8c1996ca851b04799af2405fee8c0a001a2.

**Additional info**
Default sound settings in dosemurc.  These games use MT-32 and I have dosemu compiled with MUNT.  Games that don't use the interrupt work properly.

**Comment by stsp** [comment] 2022-08-21 09:15
Have you done `emusound -es mt32`?
Use `emusound` (w/o params) to list
current settings. mt32 setup looks like
this:
```
SB at 0x220-0x22f, IRQ=5, DMA8=1, DMA16=5. MPU-401 at 0x330-0x331, IRQ=9.
MIDI synth mode is mt32
```

**Comment by jharrison03** [comment] 2022-08-21 16:54
It's the same result if I run those commands (note that I don't have the GM option set in dosemurc, and it's only the games that are specified as requiring the MPU IRQ that don't produce sound.  The bulk of MT-32 supporting titles run fine).

It's only 11 games on that list that seem to require the interrupt, so not a terribly big deal, but I know it worked at some point in the past.

emusound -es mt32
```
mt32 is already set
BLASTER=A220 I5 D1 H5 P330 T6
MIDI=SYNTH:2 MAP:E MODE:2
```

emusound
```
SB at 0x220-0x22f, IRQ=5, DMA8=1, DMA16=5. MPU-401 at 0x330-0x331, IRQ=9.
MIDI synth mode is mt32
```

**Comment by runderwo** [comment] 2022-08-21 17:00
There's never been an implementation of MPU-401 intelligent mode (i.e. hardware sequencer).  I have a private branch where I ported the dosbox implementation (along with some additional sbmidi/MPU401 related fixes), but I could not get the timing to work 100% - the tempo slowed down when keyboard or mouse was not being operated - and there was not enough interest to get to the root cause and push it over the finish line.  I still have the attempt in a private branch but it would have to be brought up to date.

**Comment by jharrison03** [comment] 2022-08-21 17:12
Thanks runderwo.  Unless I'm mis-understanding something, this is a list of "intelligent mode games".  There's 58 of them on that list.  The bulk of them work just fine -- it's only the 11 that state an MPU-401 interrupt requirement don't work.

https://github.com/bjt42/softmpu/wiki/Compatible-Intelligent-Mode-Games

Admittedly, I don't fully grasp what "intelligent mode" does, other than in the case of games, seem to co-process a timer function on the MPU-401 hardware.  

That list may be deceptive, because it leads one to believe that "intelligent mode" doesn't necessarily mean it needs to use MPU-401 IRQ.

**Comment by stsp** [comment] 2022-08-21 17:35
Please build from master (which
doesn't contain the patch you mentioned)
and see if it worked on pre9.

**Comment by stsp** [comment] 2023-08-06 07:58
This should be fixed.

**Closed as completed by stsp** 2023-08-06 07:58 UTC
